### ISSUE TITLE
Pull solidus_multi_domain into solidus

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#112]
Since there is a store model already in Solidus, a lot of the multi_domain overrides probably make sense to live in Solidus itself, rather than relying on lots of overrides in that extension.

**Comment by cbrunsdon** [comment]
A bit of history for anyone that starts this:

"spree-multi-domain" was built for pre-1.0 spree. Over time it gained more features and functionality as more people adopted it and incorporated it into their stores.

As "multi domain" (the ability to run multiple stores off of one codebase) was a very desirable feature, the "store" ActiveRecord model from spree-multi-domain was added into core so different multi-domain implementations could share at least some common ground and functionality.

It was not ever implemented as a complete set of functionality and much of the spree-multi-domain extension was relied upon to make a store actually work properly.

The core team has agreed that as much of that functionality should be pulled into solidus core as is appropriate. 

A person wanting to work on this issues could go through [solidus_multi_domain](https://github.com/solidusio/solidus_multi_domain) and evaluate all overrides and functionality, pulling out and building PR's for anything that was better suited for core.

I would consider this a very "accessible" task that could be accomplished by developers of any level.

**Comment by anulman** [comment]
Hey all—hoping to revive this thread.

Stumbled on this while [browsing source](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/store.rb#L6); my firm is about to need different `default_cart_tax_rate` lookup on our stores and would like to minimize eventual pain as Solidus expands multi-store support.

Seems easy enough to override the lookup w/ a subclass, but we'll have to persist the store's state (as in OH, CA, AZ, NY...) somehow to look this up properly.

We're using the core project as a backend for a custom frontend, so using `solidus_multi_domain` isn't a good option. Further, multi_domains options were a bit brittle; I'd figure downstream implementers may have all sorts of metadata they may want / need to add to a `Store`.

Are you open to making the [properties model polymorphic](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/property.rb#L3-L4)? Seems like doing so would accommodate `Store`s' idiosyncrasies like `Product`s', and be a nice upstream API for extensions like `multi_domain`: a pattern of join tables for metadata + subclassing to manage their effects.

Since you dropped the TODO, thought I'd reach out and offer to contrib before trying something like ☝️ on our own.

**Comment by jhawthorn** [comment]
Hello @anulman 

I don't think we would accept a PR making Properties polymorphic. The `Property` is designed specifically for displaying some attributes of Products to customers and is a poor fit for just storing arbitrary data.

Instead you might consider either the `preference` feature, which allows serializing pseudo-attributes into a `preferences` attribute on the model. Or introducing a your own `MyawesomeStore` model which `belongs_to` `Store` and holds your custom store attributes.

**Comment by anulman** [comment]
`preferences` looks great. Is usage documented anywhere higher-level than the spec / are there particularly useful reference implementations?

**Comment by danielmyasnikov** [comment]
@cbrunsdon @jhawthorn , is that still the case?

I'd love to move to `solidus_multi_domain` gem into solidus.

And fix some tests 😏 , like: https://github.com/solidusio/solidus_multi_domain/blob/master/spec/controllers/spree/api/products_controller_spec.rb#L16

**Comment by cbrunsdon** [comment]
@danielmyasnikov sorry to respond late, but absolutely, I think we're very happy to take much of whats in multi domain into core if you wanted to bite off a chunk of it.

If anyway wanted to talk specifics this is a reasonable place (though I'm closing the issue), or feel free to ping me in slack.

In general that would be a good task for anyone new that wanted to contribute some how.
