### ISSUE TITLE
Soft-deleted payment methods cause errors in admin

### ISSUE THREAD

**Issue by adammathys** [solidusio/solidus#1186]
After deleting a payment method in the admin, any references to it on past orders will lead to 500 errors. (e.g.: The show page and all events that can be triggered on `/admin/orders/:number/payments`)

**Comment by jhawthorn** [comment]
I wrote a spec and it seems to work for me

``` ruby
context 'with a soft-deleted payment method' do
  let(:order) { create(:completed_order_with_totals, line_items_count: 1) }
  let!(:payment_method) { create(:check_payment_method) }
  let!(:payment) do
    create(:payment,
      order:          order,
      amount:         order.outstanding_balance,
      payment_method: payment_method
    )
  end

  before do
    payment_method.destroy
    visit spree.admin_order_payments_path(order.reload)
  end

  it "successfully lists the payments" do
    expect(page).to have_content(payment.number)
  end
end
```

**Comment by jasonfb** [comment]
I agree with @adammathys, deleting is an anti-pattern that has cost hundreds and hundreds of hours for me personally and cost huge sums of time for the companies i have worked for.

The problem is easy to replicate, simply delete a payment method.

@jhawthorn -- your test does not cover the actual crash reported by the posted (which admittedly is somewhat vague). He was referring to the 'show' page of the payment, not the Order payment page which you have tested 

the stacktrace is as follows, I was able to reproduce this in seconds on the solidus-helloworld app:

https://gist.github.com/jasonfb/cd85451cbce6941c08ff3e334cc21941

**Comment by jasonfb** [comment]
The root of the evil is that things should never be deleted once they are referenced -- "soft-delete" is a convenience that is useful auditing, but horrible when things that shouldn't be are actually allowed to be deleted, as is the case with these payment method objects as well as products & variants. I am working on a PR to address this problem in products & variants.

For payment methods, we should move towards adding a "discontinued_at" or a "retired_at" flag to be used instead of deletion. 

I feel strongly that code littered with ```.with_deleted``` scopes (as Solidus currently is) is a serious anti-pattern and I will continue to push throughout spree to address this serious, serious problem in the software.

**Comment by jasonfb** [comment]
@jhawthorn -- you failed to mention in your statement "I wrote a spec and it seems to work for me" that you also fixed the bug using a code change in https://github.com/solidusio/solidus/pull/1190

I am documenting here for completeness. Your statement "I wrote a spec and it seems to work for me would lead one to believe that it worked the way you found it, with no code changes, which is inaccurate.

**Comment by jhawthorn** [comment]
I did think it worked initially. I talked with Adam IRL to find out that it was in fact the "show" page which was having issues.
