### ISSUE TITLE
Rails 5 Roadmap

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1272]
Rails 5.0.0.rc2 is out. With a final release probably not too far off, it's time for us to start planning our migration path.

## Soldius 2.0

As always with Solidus, one of the main concerns is making the upgrade path as smooth as possible. Having everyone able to be as close to our latest release as possible is what enables collaboration.
Upgrading to a new major rails version is already a significant task, so I don't want to burden our users with significant Solidus changes at the same time.

Solidus is too complex to be able to reasonably support multiple versions of rails. What I'd like to do instead is have a simultaneous release of the final version of Solidus 1.x (probably 1.4 or 1.5, depending on timeline) and Solidus 2.0.0. Solidus 2.0.0 should include the absolute minimum changes to allow upgrading to rails 5, and to fix any warnings.

We may remove some deprecated functionality in 2.0.0 (as the major version bump will allow us to do), but ideally I would push that off to 2.1.0.

## Current state

We have a WIP [rails5 branch](https://github.com/solidusio/solidus/tree/rails5), where things are mostly working. There are still a handful of spec failures remain in each of core, frontend, backend and a dozen or so in api.

In the current `rails5` branch, I am removing the `new_framework_defaults.rb` initializer, in order to continue using some no longer default, deprecated behaviour. We'll want to fix this before the final release so that it will work with either set of defaults.

A few gems we depend on need new versions out (ransack, paranoia, state_machines), but their `master` branches on github work with rails 5, so it shouldn't be long before these are available.

**Comment by jrochkind** [comment]
Are you sure it's unrealistic to support both rails 4 and 5?  It might be worth at least considering if that's possible, when looking at the test failures in Rails 5 and how to address them.  The changes between Rails 4 are 5 are not huge, probably smaller than between 3 and 4 -- and I've worked previously on a somewhat analagous Rails Engine that managed simultaneous rails 3 and 4 compat. (Now, Rails 2 to 3 -- forget about it!). 

But if there isn't going to be a version that supports both, then I agree the right way to do it is with a version that moves from Rails 4 to 5, with as _few_ Solidus backwards incompat as possible (including not removing current deprecated behavior). 

Another thing to do would be to consider calling that version the next solidus 1.x instead of 2.0.  Solidus declares a dependency on Rails.  Just release a 1.4 (or 1.5, or wherever we're up to then) that bumps the Rails dependency to `~> 5.0.0`, and bundler won't let them upgrade to it until they've upgraded to Rails 5 too, even if their solidus dependency in their local gemfile is `~> 1.0`.

**Comment by tvdeyen** [comment]
👎 On supporting multiple mayor Rails versions. You will end up with gazillions `if Rails.version` calls **and even worse** with `if DependencyXY.version` calls, as we can't rely on the dependencies to also support both Rails versions. In engines complex as Solidus and AlchemyCMS (which I maintain) this is nearly impossible and a huge maintenance burden. Believe me, I tried it ;)

I like the idea to only raise the Rails version and nothing else, besides changes necessary to support Rails 5 of course. 

Raising Rails version is a breaking change for lots of stores, so 2.0 is a reasonable version dump, although I don't like to raise the Soldidus mayor version just for a dependency, but I think we can't reasonably do anything else.

**Comment by jrochkind** [comment]
I've worked on a Rails engine that supported Rails 3 and 4 with few or no (can't remember for sure if it was zero) `Rails.version` checks, just a few `respond_to?` checks like good ruby.  I think it depends on the nature and number of the failures in Rails 5. 

But I can respect not trying to support both; I think changing the Rails version number with no other intentional backwards incompat is probably a good move in that case. 

I still think calling the next 1.x would be a reasonable move, to save 2.0 for actual removal of deprecated behavior and other breaking changes (the PaymentSource stuff?).  While technically a dependency only change could be considered a breaking change, I also think it could be considered not. What problems will it actually cause for anyone if it's 1.x?  Since a `bundle update` will refuse to update to the rails-5-requiring solidus version unless the local app updates it's rails dependency too, I can't think of any.

**Comment by tvdeyen** [comment]
Like I said, the problems are the dependencies (and dependencies of the dependencies) that will make us headaches. And Solidus has lots if dependencies. Engines with less dependencies are way easier to handle multiple Rails versions. 

I also would like to keep the 2.0 for Solidus related breakage, but one scenario could hold stores from updating to Solidus 1.rails5:

Stores that have dependencies besides Solidus, that may not yet be Rails 5 compatible (Alchemy for instance). So, they can't upgrade until these dependencies also support Rails 5. That's considered breaking IMO. Having a clear signal (a mayor version raise) could help here. I know these are just numbers, but this is how semver (and people understanding semver), works. 

Also, we could still work on 1.x related stuff without having Rails 5 in mind. Rails 5 compatible stuff could be ported to 2.0, while Rails 5 incompatible stuff stay in 1.x

I hope that this will never be the case, though. And maybe Rails 5 upgrades are hopefully easier then previous upgrades. (Let's never see a Rails 2 -> 3 horror ever again), but we should be well prepared. 

Anyhow, maybe I'm just too anxious after all these brutal Rails upgrades I went through over the years.

**Comment by jhawthorn** [comment]
> Are you sure it's unrealistic to support both rails 4 and 5?

Yep.

> I've worked on a Rails engine that supported Rails 3 and 4 with few or no (can't remember for sure if it was zero) Rails.version checks, just a few respond_to? checks like good ruby.

This is probably viable for small engines, but we just have too much app code.

Two examples of changes we need to make in order to support new rails 5 apps (with the new defaults) without having deprecations.

* `return false` doesn't halt callbacks anymore. We need to `throw abort`
* Every `get`/`post` in controller specs needs to be passed different arguments

**Comment by jhawthorn** [comment]
With the 2.0.0.beta1 out and master running rails 5 I think it's time to close this.
