### ISSUE TITLE
Issues with DelegatesBelongsTo module

### ISSUE THREAD

**Issue by andela-oakinniranye** [solidusio/solidus#1278]
Recently, I decided to try out some Spree models and use some modules in my application, including the `delegate_belongs_to`, everything seemed to be working fine until...

On the `Spree::Variant` table, I added a slug column, so that each variant could have a unique slug, e.g product-slug-variant-slug. When this was done, I began to see some inconsistent behaviours when I tried to read/write the value of the slug, as this always returned `nil`.

After digging through the source code a bit, I discovered that this was due to the `DelegatesBelongsTo` module, in the `delegator_for` and `delegator_for_setter` methods which were meant to return no value(fail silently) if there was a clash in column name and delegated method name, without informing the developer of this reason.

The test speaks for itself as well `core/spec/lib/spree/core/delegate_belongs_to_spec.rb`.

I would like to know if this behaviour is intentional and why? If not, I could send a PR to fix this, if anyone thinks it makes sense.

**Comment by jhawthorn** [comment]
Entirely agree that failing silently and returning `nil` is a bad behaviour. `delegate_belongs_to` is an old relic from spree early days and has a bunch of behaviour like this, which is why we deprecated in solidus 1.1 and later.

I think that an all cases it is better just to use rails's `delegate`

```
delegate :foo, :foo=, to: :some_association
```

Because this is deprecated functionality and to be removed in the future, I'd rather not make changes to it.
