### ISSUE TITLE
How to customize views HTML within solidus

### ISSUE THREAD

**Issue by acrolink** [solidusio/solidus#1291]
I have noticed that the app/views & app/controllers folders are empty. My question, how to customize HTML of the rendered pages? Which files I need to target? Thanks.

**Comment by jasonfb** [comment]
this information from the old Spree guides applies to your questions: http://guides.spreecommerce.org/developer/view.html#template-replacements

You might want to seek help on the #support channel of the Solidus Slack room.

**Comment by acrolink** [comment]
Thanks @jasonfb .. I read the documentation you pointed to .. I think this task should be easier to do than the way it is now, nothing compares to directly editing views and controllers .. What I understood is that modifying the views/controllers files is possible but that would mean editing the global ones. Maybe I can avoid this by installing solidus/spree locally within my app.

**Comment by jasonfb** [comment]
Spam detection software, running on the system "mail2.hsphere.cc", has
identified this incoming email as possible spam.  The original message
has been attached to this so you can view it (if it isn't spam) or label
similar future email.  If you have any questions, see
the administrator of that system for details.

Content preview:  Actually for views you copy the file from the gem views into
   your app (thus creating work for yourself when you upgrade and the original
   file changes --- this is why some people use deface, but deface has its own
   problems) [...] 

Content analysis details:   (5.1 points, 5.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
 2.5 HTML_IMAGE_ONLY_28     BODY: HTML: images with 2400-2800 bytes of words
 0.0 HTML_MESSAGE           BODY: HTML included in message
 2.5 MIME_QP_LONG_LINE      RAW: Quoted-printable line longer than 76 chars
 0.1 RDNS_NONE              Delivered to trusted network by a host with no rDNS

The original message was not completely plain text, and may be unsafe to
open with some email clients; in particular, it may contain a virus,
or confirm that your address can receive spam.  If you wish to view
it, it may be safer to save it to a file and open it with an editor.


X-Virus-Scan: Scanned by ClamAV 0.98.4 (no viruses);
  Sat, 02 Jul 2016 11:06:32 -0400
Received: from unknown (HELO ?100.121.54.16?) (jason.fb@datatravels.com@70.199.96.172)
  (de-)crypted with TLSv1: DHE-RSA-AES256-SHA [256/256] DN=unknown
  by mail2.hsphere.cc with ESMTPSAM; 2 Jul 2016 15:06:31 -0000
X-Originating-IP: 70.199.96.172
Content-Type: multipart/alternative;
	boundary=Apple-Mail-5B0AC797-A054-4174-8DF2-F8A028C48228
Mime-Version: 1.0 (1.0)
Subject: Re: [solidusio/solidus] How to customize views HTML within solidus (#1291)
From: Jason FB <jason.fb@datatravels.com>
X-Mailer: iPhone Mail (13F69)
In-Reply-To: <solidusio/solidus/issues/1291/230094093@github.com>
Date: Sat, 2 Jul 2016 11:06:28 -0400
Content-Transfer-Encoding: 7bit
Message-Id: <051E6450-E259-4E0B-8F74-38CA9FC4FE7D@datatravels.com>
References: <solidusio/solidus/issues/1291@github.com> <solidusio/solidus/issues/1291/230094093@github.com>
To: solidusio/solidus <reply@reply.github.com>


--Apple-Mail-5B0AC797-A054-4174-8DF2-F8A028C48228
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

Actually for views you copy the file from the gem views into your app (thus c=
reating work for yourself when you upgrade and the original file changes ---=
 this is why some people use deface, but deface has its own problems)

For controllers you use class eval and overload methods.

Having said that, for a lot of backend plumbing, many parts of Solidus have n=
ow plug-in class components (slightly newer & cleaner approach the community=
 is moving towards)

The fundamental problem is that smaller  and new stores want the ease of usi=
ng existing controllers & views but larger Spree/Solidus operations typicall=
y outgrow this and write their own frontends and keep Spree/Solidus primaril=
y as back end.

Your mileage may vary.

Sent from my iPhone

> On Jul 2, 2016, at 6:02 AM, acrolink <notifications@github.com> wrote:
>=20
> Thanks @jasonfb .. I read the documentation you pointed to .. I think this=
 task should be easier to do than the way it is now, nothing compares to dir=
ectly editing views and controllers .. What I understood is that modifying t=
he views/controllers files is possible but that would mean editing the globa=
l ones. Maybe I can avoid this by installing solidus/spree locally within my=
 app.
>=20
> =E2=80=94
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>=20

--Apple-Mail-5B0AC797-A054-4174-8DF2-F8A028C48228
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=
utf-8"></head><body dir=3D"auto"><div>Actually for views you copy the file f=
rom the gem views into your app (thus creating work for yourself when you up=
grade and the original file changes --- this is why some people use deface, b=
ut deface has its own problems)</div><div id=3D"AppleMailSignature"><br></di=
v><div id=3D"AppleMailSignature">For controllers you use class eval and over=
load methods.</div><div id=3D"AppleMailSignature"><br></div><div id=3D"Apple=
MailSignature">Having said that, for a lot of backend plumbing, many parts o=
f Solidus have now plug-in class components (slightly newer &amp; cleaner ap=
proach the community is moving towards)</div><div id=3D"AppleMailSignature">=
<br></div><div id=3D"AppleMailSignature">The fundamental problem is that sma=
ller &nbsp;and new stores want the ease of using existing controllers &amp; v=
iews but larger Spree/Solidus operations typically outgrow this and write th=
eir own frontends and keep Spree/Solidus primarily as back end.</div><div id=
=3D"AppleMailSignature"><br></div><div id=3D"AppleMailSignature">Your mileag=
e may vary.<br><br>Sent from my iPhone</div><div><br>On Jul 2, 2016, at 6:02=
 AM, acrolink &lt;<a href=3D"mailto:notifications@github.com">notifications@=
github.com</a>&gt; wrote:<br><br></div><blockquote type=3D"cite"><div><p>Tha=
nks <a href=3D"https://github.com/jasonfb" class=3D"user-mention">@jasonfb</=
a> .. I read the documentation you pointed to .. I think this task should be=
 easier to do than the way it is now, nothing compares to directly editing v=
iews and controllers .. What I understood is that modifying the views/contro=
llers files is possible but that would mean editing the global ones. Maybe I=
 can avoid this by installing solidus/spree locally within my app.</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">=E2=80=
=94<br>You are receiving this because you were mentioned.<br>Reply to this e=
mail directly, <a href=3D"https://github.com/solidusio/solidus/issues/1291#i=
ssuecomment-230094093">view it on GitHub</a>, or <a href=3D"https://github.c=
om/notifications/unsubscribe/AADmemGpgqIGQb9H3z9CSpjN_H09Ic6Xks5qRjdEgaJpZM4=
JDgu3">mute the thread</a>.<img alt=3D"" height=3D"1" src=3D"https://github.=
com/notifications/beacon/AADmeqYKHNOCY-Ber-6X-1CQjZs8N7A0ks5qRjdEgaJpZM4JDgu=
3.gif" width=3D"1"></p>
<div itemscope=3D"" itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope=3D"" itemtype=3D"http://schema.org/ViewAc=
tion">
  <link itemprop=3D"url" href=3D"https://github.com/solidusio/solidus/issues=
/1291#issuecomment-230094093">
  <meta itemprop=3D"name" content=3D"View Issue">
</div>
<meta itemprop=3D"description" content=3D"View this Issue on GitHub">
</div>
</div></blockquote></body></html>=

--Apple-Mail-5B0AC797-A054-4174-8DF2-F8A028C48228--

**Comment by acrolink** [comment]
@jasonfb Thanks, that made things clearer for me.

**Comment by jasonfb** [comment]
@acrolink Cool you are welcome. I'd suggest you close this GH issue since it isn't actually an issue, nor is the community going to take on the project of "make a better way to customize" in a Github Issue. 

Trust me, lots of people also want "a better way to customize" for Solidus but it it not something that is easily solved or trivial. The pluggable-classes thing described above is one example of the community recognizing a need for a better way and then taking a few baby steps in that direction. 

If you want to do some work to think about how you'd approach the problem, a GH issue might be appropriate for a specific proposal to fix or augment in a specific way.

Like, here's what I think we should do and here's what I propose, etc.

But in the absence of that I'm fairly certain there is nothing actionable here as at this point it sounds like you are basically taking Solidus out for a test drive.
