### ISSUE TITLE
404 Upon Checkout - Heroku Deploy

### ISSUE THREAD

**Issue by mcooney9790** [solidusio/solidus#1326]
Hi Solidus Folks,

I just recently deployed an application to Heroku and it all seemed to be working fine until I tested the checkout flow and my application seems to receive a 404 error when navigating to "/checkout/registration"

I followed the heroku guide for deploying rails applications. Is there a step I may be missing that is leaving some of the rails assets behind on my dev server?

Any help is appreciated, thanks.

Myles

**Comment by gmacdougall** [comment]
Registration isn't provided out of the box with Solidus. In order to work with a number of different authentication systems, it's extracted out to an extension such as [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise).

As we manage the issues of the project through Github, I'm going to close this and would encourage you to bring future questions or issues up in another forum like the Solidus Slack support channel.
