### ISSUE TITLE
How can we add payu payment method for solidus app. Please help me I am getting stuck.

### ISSUE THREAD

**Issue by pkumarmis** [solidusio/solidus#1345]
I have completed an e-commerce website based on solidus framework, but I want to integrate Payu Payment gateway with it, But I didn't get any solution. I found a gem netguru/spree_payu_integration but it does work with solidus.

**Comment by jasonfb** [comment]
You will probably want to write an integration for Payu. netguru/spree_payu_integration  is a good place to start. Depending on the code in that gem, you may or may not want to use that code. 

Solidus is a community-driven project, so if there is code you want to see built it is better to approach the community with the attitude of what you can offer--- i.e., build it and open source it, or build it with another company, or pay a 3d party to build it, etc--- rather than what the platform can offer you. Then again, others may have some advise specifically for Payu. (But if there is no Payu integration, you'll have to consider how you want to proceed as Solidus is just a Ruby platform, it is not a service.)

if I were you I'd fork netguru/spree_payu_integration and start to play around with it to see if you can get it working with Solidus. (Raname it solidus_payu_integration while you're at it.)

**Comment by jasonfb** [comment]
You might also want to ask on the Slack channel, under the #support room, which you can find here: http://slack.solidus.io
