### ISSUE TITLE
Why do we store currency on line items

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#1399]
Given:
- Orders have a currency
- We don't want to allow orders with line items of varying currencies

Could we remove currency from line items and instead delegate it to the order?

**Comment by gmacdougall** [comment]
We can likely remove currency from LineItem. When I was originally adding support for currencies, I went in with a very basic assumption: everywhere that has an amount which is representing money gets a currency.

It was probably a mistake to add it to LineItem rather than rely on a join or delegation to make it happen.

**Comment by mamhoff** [comment]
I have tried to remove it in the prices refactoring, but at the time we felt it to be unrelated, so I axed that change. I still would like to see that gone.

**Comment by kennyadsl** [comment]
I'm working on this issue, for now I only made [this commit](https://github.com/nebulab/solidus/commit/48dc2f0b12a991b485a7a17033703a919271a3a2). I'm not sure how to proceed in terms of validation. If there's no `Spree::Price` with the currency of the current order, the line item will have nil price. Is this something that could happen or we always have a price in each currency?

**Comment by mamhoff** [comment]
Hey @kennyadsl - I looked through the code and have issues with it :) - By default, a user should only be shown products and variants that have a price in the current currency (that's why the `Variant.with_prices` [scope] exists). (https://github.com/solidusio/solidus/blob/master/core/app/models/spree/variant.rb#L109-L112]). The default product searcher, which is used in the standard frontend products controller, will also exclude products without matching prices: https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/search/base.rb#L32-L34

I think the line item should be invalid and error out if no price with the right pricing options can be found.

**Comment by kennyadsl** [comment]
Hey @mamhoff , thanks for reading my commit. 

I think that check is done [here](https://github.com/nebulab/solidus/commit/48dc2f0b12a991b485a7a17033703a919271a3a2#diff-d4464f8dddd86dd147739f1fcf6d589bR186) and tested [here](https://github.com/nebulab/solidus/commit/48dc2f0b12a991b485a7a17033703a919271a3a2#diff-e2c80773d9997dad992b4f6754a00847R146). Anyway there's still something to fix there, probably also find better names for errors and validation method. What do you think?

**Comment by mamhoff** [comment]
Hey @kennyadsl I left some comments on the commit itself; I think we can simplify things a little bit more as some of the stuff in there has been deprecated for a while already.

**Comment by kennyadsl** [comment]
@mamhoff thanks, I'll do changes in the direction proposed and go ahead with a PR asap.

**Comment by kennyadsl** [comment]
@mamhoff please check progresses on #1507

**Comment by jhawthorn** [comment]
Finished in #1507 :tada:
