### ISSUE TITLE
Why all in one ?

### ISSUE THREAD

**Issue by tibastral** [solidusio/solidus#1412]
Hello everyone,

I was wondering why are you putting everything inside one single repository (instead of separated repositories) for solidus (api / backend / frontend / core / sample) ?

Thank you very much.

**Comment by mamhoff** [comment]
Mainly, for two reasons: 

1. The Spree project, from which Solidus forks, has started out like that, and we're very keen on preserving the commit history of the project. 

2. Changes in one part of the project very likely affect the other parts. When we review changes, we want to run the test suite against all of them so we know when we break things.

**Comment by tibastral** [comment]
Ok understood. But if we want to improve one part (say the graphic design of the backend), wouldn't it easier if everything was separated in different repos ?

**Comment by jrochkind** [comment]
What would make it easier to improve (eg) the graphic design design of the backend if everything were in separate repos, what is challenging for you about it being one repo?

Are you talking just about code structure in repositories, or are you talking about "release management" issues, how the gems are compatible with each other?

**Comment by tibastral** [comment]
Imagine I want to fork the frontend gem, but I don’t want to fork everything else. Would be easier if the gem was separate.

—
Thibaut

On 1 septembre 2016 at 17:52:02, Jonathan Rochkind (notifications@github.com) wrote:

What would make it easier to improve (eg) the graphic design design of the backend if everything were in separate repos, what is challenging for you about it being one repo?

Are you talking just about code structure in repositories, or are you talking about "release management" issues, how the gems are compatible with each other?

**Comment by jrochkind** [comment]
I don't understand what's harder about 'forking everything else'.  It's just a single `git clone` statement and/or github "fork" button depending on how you do it. It's the same either way, if it's the entire solidus repo or a repo just for one of the gems. 

What is making it harder for you when it's all of the gems in one repo? It's still just a single command, I'm not clear on what is hard about it. 

Have you done this yet, or are you just worried about it? I'd suggest giving it a try, I don't think you are going to find it a problem. 

If you want to have an app that depends on your custom forked version of just one of the solidus gems but uses standard releases for the others -- you can definitely still do that, no problem. If that's what you're worried about.

**Comment by tibastral** [comment]
Ok. Let's say it another way (BTW thank you for taking the time to answer to me).

I want to change the frontend, but to stay mainstream with the other parts of solidus (especially the core).

Possibly my pull requests will change a lot of things, so you won't be able to merge them.

Imagine we are in the gems world where the frontend gem is different from the core gem. And you update the core gem. If I want to update my frontend gem in order to make it work with the new core, I just have to put the new version inside the gemspec of the frontend gem and make the frontend tests pass and that's it.

Right now if I want to change the frontend part, and someone update the core, I will always have to rebase or merge it inside my branch and possibly I'll have a ton of modifications inside the frontend I don't want, but I won't be able to rely on the gems versioning.

**Comment by jrochkind** [comment]
You can still use a forked version of `backend`, while using release versions of everything else. It does, you're right, require a bit more work on your end, as `bundler` won't point at a subdirectory of a `git` repo. But it's still possible.   

One way to do it would be to checkout the solidus repo (or your fork) locally, probably put it in `./vendor`, and then use bundler `path` to point directly to the `core` subdirectory for the `frontend` gem, but keep using ordinary releases from rubygems for all other gems. You'd probably want to do this as a git submodule, so your `vendor` copy still has a git connection to your forked repo, and you can still pull and such. 

You don't need to include the umbrella `solidus` gem in your Gemfile, you can include each individual solidus Gem in your Gemfile directly, with different sources. `gem 'solidus_frontend', path: 'vendor/solidus/core` ; gem 'solidus_backend'` etc.  Maybe you didn't realize you can specify each individual gem separately in your gemfile, even though they are in the same repo and even though there is the umbrella `solidus` gem?

In any case, you'll have to deal with merge conflicts with the stuff you edited in `frontend`. You shouldn't have any merge conflicts anywhere else since you aren't touching code anywhere else. 

Compare to [rails](http://github.com/rails/rails) which is set up very analagously. There is a gem `rails` which consists solely of dependencies on `activerecord`, `actionpack`, etc.  You can list the umbrella `rails` in your Gemfile -- or you can list each individual gem separately, which is usually done if you want to leave one out (say you don't need `activerecord`), but can also be done if you want different sources for different gems.  All rails gems are in the same rails repo, in subdirectories, with their own gemspecs. 

The workflow you suggest, of running off a custom local fork of a solidus gem in production, is, if I understand right (I'm not a committer), not recommended by solidus, not a use case that is prioritized, probably not a great idea, not the way solidus intends itself to be used. 

But if you want to do it, you still can. It is slightly more inconvneient, I agree, because you have to deal with git submodules or some other mechanism that will accomplish similar.

**Comment by tibastral** [comment]
Thanks for the explanation, will try it this way :)

—
Thibaut

On 2 septembre 2016 at 14:30:36, Jonathan Rochkind (notifications@github.com) wrote:

You can still use a forked version of backend, while using release versions of everything else. It does, you're right, require a bit more work on your end, as bundler won't point at a subdirectory of a git repo. But it's still possible.

One way to do it would be to checkout the solidus repo (or your fork) locally, probably put it in ./vendor, and then use bundler path to point directly to the core subdirectory for the frontend gem, but keep using ordinary releases from rubygems for all other gems. You'd probably want to do this as a git submodule, so your vendor copy still has a git connection to your forked repo, and you can still pull and such.

You don't need to include the umbrella solidus gem in your Gemfile, you can include each individual solidus Gem in your Gemfile directly, with different sources. gem 'solidus_frontend', path: 'vendor/solidus/core ; gem 'solidus_backend'etc. Maybe you didn't realize you can specify each individual gem separately in your gemfile, even though they are in the same repo and even though there is the umbrellasolidus` gem?

In any case, you'll have to deal with merge conflicts with the stuff you edited in frontend. You shouldn't have any merge conflicts anywhere else since you aren't touching code anywhere else.

Compare to rails which is set up very analagously. There is a gem rails which consists solely of dependencies on activerecord, actionpack, etc. You can list the umbrella rails in your Gemfile -- or you can list each individual gem separately, which is usually done if you want to leave one out (say you don't need activerecord), but can also be done if you want different sources for different gems. All rails gems are in the same rails repo, in subdirectories, with their own gemspecs.

The workflow you suggest, of running off a custom local fork of a solidus gem in production, is, if I understand right (I'm not a committer), not recommended by solidus, not a use case that is prioritized, probably not a great idea, not the way solidus intends itself to be used.

But if you want to do it, you still can. It is slightly more inconvneient, I agree, because you have to deal with git submodules or some other mechanism that will accomplish similar.
