### ISSUE TITLE
Error with sample product images not loading

### ISSUE THREAD

**Issue by andreylyand** [solidusio/solidus#1418]
Hey,

I'm been trying to figure out all weekend why the product images do not load when I set up a new app. 

I added:
gem 'solidus', github: 'solidusio/solidus'
gem 'solidus_auth_devise'

Run:
bundle exec rails g spree:install
bundle exec rails g solidus:auth:install
bundle exec rake railties:install:migrations

bundle exec rake db:migrate
bundle exec rails s
 
Visit:
 http://localhost:3000/

This is what I get:
![img_4893](https://cloud.githubusercontent.com/assets/8380089/18281993/1f50f340-742d-11e6-98c4-bb1d975df83e.jpeg)

I searched the web, but haven't came up with the correct answer. I have ImageMagick installed.

**Comment by andreylyand** [comment]
I was using Windows, I have installed Ubuntu, set the app up again, and now everything works!

**Comment by mamhoff** [comment]
This is very interesting - might be a thing with path delimiters (`/` vs `\`) that we're not doing well.

**Comment by peterberkenbosch** [comment]
I think it's the ImageMagick -> Paperclip. That has been proven to be a nightmare on windows most of the times. Has been a while that I've seen these problems though.

**Comment by jhawthorn** [comment]
None of the regular solidus contributors run windows, so it is unlikely to work flawlessly. As Peter suggests, issues are likely to be with paperclip. It doesn't make sense for us to improve windows support since that won't be used for production servers, and it isn't particularly well supported by rails itself.

Glad to hear everything works on ubuntu.
