### ISSUE TITLE
Promotion eligibility? ambiguous behavior

### ISSUE THREAD

**Issue by deodad** [solidusio/solidus#1437]
On 1.3 (and on):
1. Create a coupon promotion that applies a discount to line items
2. Add a non-promotionable product to the cart
3. Add a promotionable product to the cart
4. Apply coupon

Expected behavior: the promotion applies to one line item but not the other
Got: the order is ineligible for this coupon

This is being missed due to a logical discrepancy in the [spec](https://github.com/solidusio/solidus/blob/v1.3/core/spec/models/spree/promotion_spec.rb#L511-L528):
there are two test cases in "eligible?" that aren't both possible:  
"and at least one item is non-promotionable" should be return false
"and at least one item is promotionable" should return true

What should the case where one is promotionable and is isn't? Both cases can't be right.

I'm guessing this arises from having both Order and LineItem level promotion actions, so I'm not sure how to resolve. Looking for guidance and I'll work on a PR.

**Comment by softr8** [comment]
On it

**Comment by loicginoux** [comment]
Any news on this ? I have an issue that looks really similar.
I have one product on my order, with a line item promotion adjustment applied to it (10% discount on the product). I add a second product with `promotionable = false` to the cart and the promotion on the first product is canceled, more precisely it's still eligible but the amount is set to 0.

After adding the second product, the promotion eligibility is recalculated. it's still found the line item promotion eligible.
We also recalculate its amount. 
At this point the `Spree::Promotion::Actions::CreateItemAdjustments#compute_amount` return `0` because of this line:
```
return 0 unless promotion.line_item_actionable?(order, adjustable)
```
this is because in `promotion#line_item_actionable?` the promotion is not eligible at the order level:

```
if eligible?(order, promotion_code: promotion_code) # return false
```
because the order is "blacklisted" in `promotion#eligible?`.

### 2 quick suggestions for a fix:

- First one, in `line_item_actionable?` we remove the condition on 
```
if eligible?(order, promotion_code: promotion_code)
```
- Second one, this method `promotion#line_item_actionable?` is not necessary and we should replace it everywhere by `promotion#eligible?(line_item)`

**Comment by adaddeo** [comment]
Closing as stale.

**Comment by loicginoux** [comment]
Sorry I don't understand why you close it ? I think there is still a bug, I was asking what would be a good path for a fix and didn't have any response since.  
Is it that a ticket without active discussion should be closed automatically ?

**Comment by cesartalves** [comment]
According to @kennyadsl, "Order level promotions have been downgraded to second class citizens, if not deprecated".

This issue refers to version 1.3, and we will need to take a look if the problem still makes sense / applies.

**Comment by adammathys** [comment]
I don't believe this issue is relevant with the new promotion system, and we have no plans for making future changes to the legacy one.

**Comment by fthobe** [comment]
@adammathys yes, the bug is still present.

**Comment by adammathys** [comment]
@fthobe We never fixed the bug in the legacy promotion system. It is not present when using the new promotion system. (And can be verified by reading the code. The new promotion system has a [single reference to `promotionable?`](https://github.com/solidusio/solidus/blob/main/promotions/app/models/solidus_promotions/order_adjuster/discount_order.rb#L51-L59) which shows that it uses it to filter for a list of line items that can have a promotion applied to it.)

Here's a screenshot of a sandbox store where I marked tote bags as unpromotable then applied a $10 off coupon to the cart. As you can see, it successfully applied the promotion to the non-tote bags.

<img width="1435" alt="Image" src="https://github.com/user-attachments/assets/6f582f81-a587-473d-af94-9436ac6da918" />

<img width="1545" alt="Image" src="https://github.com/user-attachments/assets/665b60b1-a325-4e33-86e9-e4f70ead7b5b" />

**Comment by fthobe** [comment]
@adammathys thank you for the time you took too track it down. It looks like I am on to something else at will open a new issue.

**Comment by fthobe** [comment]
@adammathys 

Same outcome different bug then: 
- "Solidus Water Bottle copy" is not promotable 
- "Solidus Water Bottle" is
- Coupon code configuration in screenshot below

Coupon can not be applied to an order that cointains both items. 

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/0b014948-e097-425b-8240-852f247ceca4" />

<img width="1272" alt="Image" src="https://github.com/user-attachments/assets/cbbfd621-c1e5-4c74-803a-7ef38d384cbd" />

**Comment by adammathys** [comment]
@fthobe The screenshot of your promotion admin is from a legacy promotion. The new promotion system doesn't have rules and actions, it uses "benefits" and "conditions."

It should look something like this:

<img width="1404" alt="Image" src="https://github.com/user-attachments/assets/4e0f48af-8d3b-41bd-aecf-8bdad49f3c8a" />

**Comment by fthobe** [comment]
@adammathys hey thank you for your reply. I was told already. We have opened a ticket for documentation as there are inconsistencies in between blog, release notes and promotion documentation. I have never touched solidus before 4.4 and it was written that the new promotions are installed by default on new installations (which they are not). Therefor this issue was closed.
