### ISSUE TITLE
Decide on / bring a product bundling solution into core.

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#144]
There are a few different implementations so far, and it could be nice to have a single recommended way of bundling products together.

**Comment by cbrunsdon** [comment]
I'm looking at "yet another mapping system" on a Spree 2.4 (which will shortly-ish go solidus) to map line items -> ??? -> multiple inventory units.

I'm having an initial discussion with Hawth and Jared on some of the systems we've already built and seeing what comes out of it. After that I'd like to talk to you @athal7 more about what you've done with bundles if you have a bit of time.

**Comment by athal7** [comment]
@cbrunsdon can you say more about that mapping system? I'm curious to understand what you mean by that. happy to chat about bundles anytime

**Comment by cbrunsdon** [comment]
Just to give some background to anyone reading this in the future (and anyone feel free to correct me if I'm wrong anywhere here) there are two different ways this has been done.

The first is a "mapping" system that maps a specific line item (or more likely, a line item's variants) to different stock items. When shipments are being created, rather than the line item's variants being added to a shipment, all the variants that are "mapped" get added instead. This is how something like spree-product-assembly works, or a few things we haven't been able to make public.

This method is:
* Easier to make promotions on (as we can look at line-items individually)
* Is much harder to track which line items inventory units came from (since they go through some mapping process)
* Makes tracking stock on the line items very difficult (as we need to know the state of all mapped items)
* Works well if mappings are "dynamic" and fulfilment can be handled by a selection of variants on the backend

The other implementation is a "product bundles", which isn't currently public but the folk at Bonobos have in a state that could be shared relatively easily. Instead of handling the mapping of a line item to inventory units, it adds multiple line items to your cart when a "bundle" is added. This is the system I want more clarification on, but my immediate thoughts on it are:

* Makes it very clear in a "cart" which items you're actually getting (which is desirable sometimes but not all times)
* Has potentially less inventory complications as we know the variants that will be added as we check out
* Makes it harder to write promotions for (think: %off if entire bundle is purchased, but a user could remove one of the variants in the cart)

**Comment by athal7** [comment]
Thanks for the write up. That's my understanding of the options as well

**Comment by chornodid** [comment]
@cbrunsdon Did you consider to add bundle id in case of "product bundle" solution so that you can eliminate the problem with promotions (you can check at any moment if a bundle is entire or not)

**Comment by cbrunsdon** [comment]
We don't have a clear winner on how to do bundling, and there isn't a clear path forward anyone is working on they want in so I'm closing this. If anyone was specifically attempting this themselves, happy to re-open the issue.
