### ISSUE TITLE
Store Credit History Balance Not Treated Independently

### ISSUE THREAD

**Issue by gmacdougall** [solidusio/solidus#1473]
Each individual store credit does not treat its "Total Unused" independent from other store credits.

For example:

![image](https://cloud.githubusercontent.com/assets/764390/18876567/36df3f8c-8498-11e6-9781-3e372f5757d0.png)

This store credit shows as having $127.96 unused despite the fact that this particular store credit is only for a total of $50. This is because there is another store credit which has the additional $77.96 available.

**Comment by mtylty** [comment]
I'm working on this and probably almost done... 

I have one doubt though... Should we keep the `user_total_amount` column on the `spree_store_credit_events` table or can we just rename the column?

I'm asking because I just can't figure out why something like that should be saved in the `Spree::StoreCreditEvent` model even though I'm sure it must have some kind of logic behind it...

**Comment by gmacdougall** [comment]
I would probably keep the column and add a new column to track the amount remaining amount on this particular store credit. That way we don't break backwards compatibility or people who rely upon it in their application.

We're looking at doing some work to deprecate store credit events with a proper accounting ledger which will deprecate StoreCreditEvents to be removed in a future version of Solidus.

**Comment by mtylty** [comment]
Do you have some work planned to deprecate StoreCreditEvents, refactor the code and then close this bug?

Because if you think it's not worth it to fix this bug before the refactor I'd better stop and work on some other issue 😄.
