### ISSUE TITLE
Canonical Link Incorrect (SEO)

### ISSUE THREAD

**Issue by rsiddle** [solidusio/solidus#1549]
The /products URL needs to have the trailing slash removed[1]. The non-trailing slash is linked to throughout the website:

```
<link href="http://localhost:3000/products/" rel="canonical" />
```

However, it should be:

```
<link href="http://localhost:3000/products" rel="canonical" />
```

Environment:
- Ruby 2.3.0
- Solidus 2.0.0

Sources:
[1] https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

**Comment by kennyadsl** [comment]
I think it works the way it currently is. As far as I understood from the post you linked you don't have to pick the right version of the URL in the canonical tag, you should just pick one version and be consistent. Both `/products` and `/products/` return `200` so they are equivalent. 

Ok, which one is the most correct version? Since `products#index` is a collection route I think it's correct to have a canonical tag for this route with trailing slash, since it's like saying to search engines that this resource has something inside (products), like a directory.

**Comment by jrochkind** [comment]
It works the way it currently is, but Google recommends using the same version of the URL in most of your internal links as the canonical URL -- which makes a lot of sense. If they don't currently match, as it appears they do not, it's probably easier to change the canonical URL than to change all internal links.

**Comment by rsiddle** [comment]
@jrochkind That's correct. Google treats URLs separately based on their underlying character code (the original source link I posted shows the examples, with them mentioning the 200 status response). The following URLs may seem the same, but they are evaluated differently:

* http://example.com/test
* http://example.com/Test
* http://example.com/TEST
* http://example.com/test/
* http://www.example.com/test
* https://example.com/test
* https://www.example.com/test

It's best to use the non-trailing slash consistently

**Comment by kennyadsl** [comment]
@rsiddle as far as I understood they are evaluated differently if there's no a consistent (always same) canonical tag in those pages.

**Comment by rsiddle** [comment]
@kennyads The canonical tag is an indicator to show which page your want Google to rank. At the moment, the internal links are all pointing to the non-trailing slash, which is a very strong indicator that it's the correct URL. The product index page then has a canonical tag which states that another URL is the desired URL (with trailing slash). By removing the trailing slash from the canonical tag, we're telling Google that we want to use the desired (non-trailing slash) version.

**Comment by jhawthorn** [comment]
I agree it would be better to lose the trailing slash.

`canonical-rails` [adds this](https://github.com/jumph4x/canonical-rails/blob/master/app/helpers/canonical_rails/tag_helper.rb#L4) for [index actions](https://github.com/jumph4x/canonical-rails/blob/master/lib/canonical-rails.rb#L24) (I have no idea for what reason)

**Comment by kennyadsl** [comment]
maybe it's just matter of setting an empty array [here](https://github.com/solidusio/solidus/blob/master/frontend/config/initializers/canonical_rails.rb#L8)?

**Comment by cbrunsdon** [comment]
I've noticed this come up in our analytics before, I don't think its reasonable to even expect just external links to be rendered correct and consistently, as other people could share a link with the extra trailing slash.

I'd be for setting the canonical link on the product page to what is proposed :+1:

**Comment by mtomov** [comment]
@jhawthorn  - reason is that index pages represent a _collection_ of items, aka a _folder_ , which is why it is more semantically correct to use a trailing slash on index pages. An ending trailing slash represents a multitude of resources, while no trailing would represent one.

On the google link at the top, it's the first example:

> http://example.com/foo/ (with trailing slash, conventionally a directory)

But indeed, Rails's path helpers do not have the canonical rails behaviour embedded, so I agree that it's best to correct the canonical tag as the author proposes.

**Comment by jumph4x** [comment]
Jumping in here late but @mtomov nailed the reasoning, however, that old school convention may not be serving the community anymore.

**Comment by jumph4x** [comment]
https://rubygems.org/gems/canonical-rails/versions/0.2.7

**Comment by kennyadsl** [comment]
@MFRWDesign asking since you did the PR on the canonical-rails: do you think we can close this one or the new option introduced needs to be explicitly called in Solidus somewhere before this to take effect?

**Comment by jarednorman** [comment]
This is probably worth doing for [Solidus Starter Frontend](https://github.com/solidusio/solidus_starter_frontend), but I don't think we're going to be doing any of this work in core against solidus_frontend, so we can close this issue.

If someone wants to open a new issue to discuss how we handle this in the starter frontend, feel free.
