### ISSUE TITLE
InsufficientStock during package creation

### ISSUE THREAD

**Issue by masterkain** [solidusio/solidus#1594]
I tested the latest release solidus version with a vanilla setup.

after a seed do this:

1) Create a new stock location
2) edit the stock for a product, set 1 on hand in the default stock location and 1 on the one you created, remove the backorderable flag on both
3) go on frontend, add 2 of this product to cart
4) proceed and go up until the delivery step
5) observe this:

```
Spree::Order::InsufficientStock in Spree::CheckoutController#update Was only able to package 1 inventory units of 2 requested`
solidus_core (2.0.0) app/models/spree/stock/coordinator.rb:135:in `validate_packages'
solidus_core (2.0.0) app/models/spree/stock/coordinator.rb:26:in `packages'
solidus_core (2.0.0) app/models/spree/stock/coordinator.rb:13:in `shipments'
solidus_core (2.0.0) app/models/spree/order.rb:507:in `create_proposed_shipments'
```

**Comment by masterkain** [comment]
This doesn't seem to keep track of quantities. Originally I tested with another setup.

3 variants, S M L
3 stock locations, A B C

each stock location has one of each variant, so stock location A has 1 on hand of S, 1 on hand of M and one on hand L, and so on.

add 3 S, 1 M and 1 L to the cart, proceeed to checkout, you'll get a `Was only able to package 3 inventory units of 5 requested`

**Comment by jhawthorn** [comment]
Yep. This is broken. See #583

In spree 2.4 the existing `Stock::ContentItem` was changed from a struct which requested a quantity of some variant to a wrapper around an unsaved inventory unit, which also locks it to a specific stock location. Because of this mistake, packaging across stock locations doesn't work.

At some point I'd love to fix this, but I'm afraid that it can only be done with a major breaking change to the Stock system (essentially reverting the 2.4 change).

**Comment by masterkain** [comment]
this seems to work for me https://github.com/nebulab/solidus/commit/4f2f5ee9d15af9996ce1f0fb47157da7443c0299 you might want to consider
