### ISSUE TITLE
Duplicate Variant shown with Variant Having multiple product

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1654]
## Setup:

- define TaxCategory to have a TaxRate with tax included in price
- create product with multiple Variant

## How to see the issue:

In the SolidusFrontend, view the product

## ScreenShot:

![image](https://cloud.githubusercontent.com/assets/1553760/21250974/82b8847e-c384-11e6-8bb0-1ab3dfbac690.png)

**Comment by flyfy1** [comment]
@mamhoff What's your idea about this issue?

**Comment by cbrunsdon** [comment]
@flyfy1 can you paste a snippet or something of some factory code that would exactly expose this problem on the sandbox? Would help a lot for debugging purposes.

**Comment by isindexer** [comment]
Hi @flyfy1 
Did you solve this issue ?

**Comment by seand7565** [comment]
@flyfy1 @mamhoff Having trouble replicating this issue. I've done the following: 

Changed the tax rate to "include in price"

![image](https://cloud.githubusercontent.com/assets/5720486/26301141/2ca7bd3c-3ed8-11e7-9819-4cebacf9e36d.png)

Created a product with multiple variants and assigned it the tax category

![image](https://cloud.githubusercontent.com/assets/5720486/26301178/45c0b256-3ed8-11e7-9b09-0503834933f9.png)

However I see the correct amount of variants on the product page:

![image](https://cloud.githubusercontent.com/assets/5720486/26301232/73923e8e-3ed8-11e7-86b4-f732aa6ada77.png)


This issue was from 2016 and there hasn't been any update on it since - is this still a problem?

**Comment by sechix** [comment]
Hello, I have the same problem, how did you fix it?

**Comment by seand7565** [comment]
@sechix Can you take us through the steps to replicate this problem on a clean server? I was unable to replicate this issue following the steps detailed in the initial post. Also: What version of Solidus are you on?

**Comment by mntmn** [comment]
I'm having the same problem with 2.5.0beta2. Also the variant prices don't include the taxes but add them on top, even if specified otherwise.

[http://dump.mntmn.com/solidus-variants-bug.png](http://dump.mntmn.com/solidus-variants-bug.png)

**Comment by mntmn** [comment]
The reason is that `variants_and_option_values_for` creates a query that contains something like this:

`... AND ("spree_prices"."country_iso" = 'DE' OR "spree_prices"."country_iso" IS NULL) `

So if you have a variant price with the "Any country" in addition to a specific country, you'll get the variant once for the specific country (DE here) and once for "Any"/NULL. The fix would be to boil it down to unique variants here. My current workaround is to delete the "Any country" price.
