### ISSUE TITLE
Are we supposed to transfer a ready shipment to another stock location?

### ISSUE THREAD

**Issue by kooinam** [solidusio/solidus#1684]
The UI show that we are allowed to transfer a shipment in READY state to another stock location but InventoryUnit did had destroy validation that forbid destroying associated with shipment in READY state. Is that a bug?

> line 135 in inventory_unit.rb   

```
    def ensure_can_destroy
      if !backordered? && !on_hand?
        errors.add(:state, :cannot_destroy, state: state)
        throw :abort
      end

      unless shipment.pending?
        errors.add(:base, :cannot_destroy_shipment_state, state: shipment.state)
        throw :abort
      end
    end
```

**Comment by kennyadsl** [comment]
This seems to be related to #97. Looking at [transfer to location code](https://github.com/solidusio/solidus/blob/712fbf6ec73467cda399d1eee1b6ea211cf1969d/core/app/models/spree/shipment.rb#L323-L338), when we [remove the line item from order contents](https://github.com/solidusio/solidus/blob/d06cfeaf066c467e00daa724dc54864906e8d88d/core/app/models/spree/order_contents.rb#L116) it also [destroys all line item inventory units](https://github.com/solidusio/solidus/blob/d06cfeaf066c467e00daa724dc54864906e8d88d/core/app/models/spree/line_item.rb#L38). [Specs are passing](https://github.com/solidusio/solidus/blob/d06cfeaf066c467e00daa724dc54864906e8d88d/core/spec/models/spree/shipment_spec.rb#L29) because it uses an order factory that has a `pending` shipment state and probably, using auto-captured payments, will automatically move shipments into ready state, making not possible to transfer an item into another stock location.

I think what we currently have is not the expected behavior, we should let users transfer content of a ready shipment into another stock location.

**Comment by kooinam** [comment]
So is it safe to replace  

> unless shipment.pending?

to

> if !shipment.pending? and !shipment.ready?

because the things is the UI is currently allowing transferring stock location for a shipment in READY state

**Comment by kennyadsl** [comment]
Honestly, I'm not sure if we'll have unexpected side effects allowing to destroy inventory units of ready shipments. Probably it's better to wait for someone else opinion/comment.

**Comment by mamhoff** [comment]
We discussed this in core, and we think this is an oversight. The `transfer_to_*` methods on `Spree::Shipment`, however, do have a number of other strange side effects: If the price of your line item is somehow different from the variant's price, the new line item you obtain after doing a full split (fulfilling all inventory from another stock location) will the variant's default price. 

Also, going through `order.contents.{add, remove}` makes this operation really slow for shipments with many inventory units.
