### ISSUE TITLE
User address not added to order after signing in

### ISSUE THREAD

**Issue by aaronrussell** [solidusio/solidus#1811]
### Reproduce

Given:
* I am a registered user with an address
* I am **not logged in**
* I have some items in my cart and am on the cart page

When:
* I click to proceed with checkout
* I am redirected to the login page
* I fill in my login details and click submit
* I am redirected to the checkout address step
* And my address is **not displayed** in the form

Expected:
* I expect my existing address to populate the order

*The above behaviour only occurs when following the steps above. If I am already logged in, then go to my cart and proceed to checkout, my existing address is correctly populated as expected.*

### System

* solidus - 2.1.0
* solidus_auth_devise - 1.6.2
* rails - 5.0.0

**Comment by mtomov** [comment]
I could tell you why that happens, though I don't have a solution proposal:

[#assign_default_addresses! in Checkout](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order/checkout.rb#L93) is the one doing the magic, but only when you change the state of the order from `cart` to `address`. That actually happens when you click Checkout, irrespective if you are logged in or not.. 

So, the state `move` happens already before you are being redirected to log in, so after you log in, and get to the address page, there is no `state` change to trigger this method to run again.

```sql

Started PATCH "/cart" for 127.0.0.1 at 2017-03-31 12:00:42 +0100
Processing by Spree::OrdersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"T4PkR/ARxR+9K4yvWQO/oOV1O1qxxWx7/UoriZ2fc6A0+V/Ey23cmyUxszFBE8j2cAq3sZHZ7pNtvmurZ98vBQ==", "order"=>{"line_items_attributes"=>{"0"=>{"quantity"=>"1", "id"=>"3"}}, "coupon_code"=>""}, "checkout"=>""}

  .............

  SQL (0.2ms)  UPDATE "spree_orders" SET "state" = ?, "updated_at" = ? WHERE "spree_orders"."id" = ?  [["state", "address"], ["updated_at", 2017-03-31 11:00:42 UTC], ["id", 3]]

  SQL (0.4ms)  INSERT INTO "spree_state_changes" ("name", "previous_state", "stateful_id", "stateful_type", "next_state", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["name", "order"], ["previous_state", "cart"], ["stateful_id", 3], ["stateful_type", "Spree::Order"], ["next_state", "address"], ["created_at", 2017-03-31 11:00:42 UTC], ["updated_at", 2017-03-31 11:00:42 UTC]]
Completed 302 Found in 123ms (ActiveRecord: 59.0ms)

Order R758931254 transitioned from cart to address via next
Redirected to http://localhost:3000/checkout/address



Started GET "/checkout/address" for 127.0.0.1 at 2017-03-31 12:00:42 +0100
Processing by Spree::CheckoutController#edit as HTML
  Parameters: {"state"=>"address"}

....

Redirected to http://localhost:3000/checkout/registration
Filter chain halted as :check_registration rendered or redirected

..

Started GET "/checkout/registration" for 127.0.0.1 at 2017-03-31 12:00:42 +0100
Processing by Spree::CheckoutController#registration as HTML
```

**Comment by kennyadsl** [comment]
What about adding [here](https://github.com/solidusio/solidus_auth_devise/blob/979cff481e45341dde2755a133970532464b4913/lib/controllers/frontend/spree/checkout_controller_decorator.rb#L16) something like this:

```ruby
current_order.assign_default_addresses! if current_order.has_checkout_step?(:address)
```

Maybe the only downside is that having this assignment in two places (and one of them is an external extension) it will be harder to debug and understand what happens in case of errors.

cc @mtomov

**Comment by aaronrussell** [comment]
Thanks - that's pointed me in the right direction. I've solved this in my app by overriding `CheckoutController#before_address` in a decorator:

```ruby
def before_address
  # It's safe to call assign_default_addresses! here as it does nothing if order has no user
  # and won't override an existing address on the order
  @order.assign_default_addresses!

  # if the user has a default address, a callback takes care of setting
  # that; but if he doesn't, we need to build an empty one here
  default = { country_id: Spree::Country.default.id }
  @order.build_bill_address(default) unless @order.bill_address
  @order.build_ship_address(default) if @order.checkout_steps.include?('delivery') && !@order.ship_address
end
```

**Comment by mtomov** [comment]
@kennyadsl that sounds like the right direction, though I am thinking that it will spread the logic too much if we add such a line to auth Devise. However, looking at the second like that you gave, I noticed [`after_action :set_current_order, only: :create`](https://github.com/solidusio/solidus_auth_devise/blob/979cff481e45341dde2755a133970532464b4913/lib/controllers/frontend/spree/user_sessions_controller.rb#L14), which I think might be just what is needed here.

See [its implementation](https://github.com/solidusio/solidus/blob/054e4bd75c65166d316f3f63be85efb48736bcdb/core/lib/spree/core/controller_helpers/order.rb#L60-L66).

**Comment by kennyadsl** [comment]
Probably @aaronrussell solution is better than mine since it does not require to change external extensions and will work no matter which controller will intercept/redirect to the checkout.

@mtomov Are you suggesting to move the `order.assign_default_addresses!` call from the state machine logic to the `set_current_order` method at controller level instead of duplicating it? I'd be less confident doing that because probably we'll lose that behavior (using an old user address) if the order is placed via API or programmatically, right?

**Comment by kennyadsl** [comment]
I'm on this one!
