### ISSUE TITLE
Promotions with multiple codes: codes locked and cannot be edited or created

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#1819]
I’ve created a brand-new Solidus store using the head of the `v2.0` branch. I go to create a promotion with multiple codes like so:

<img width="1280" alt="screen shot 2017-04-03 at 6 45 02 pm" src="https://cloud.githubusercontent.com/assets/2460418/24638555/354ba760-189e-11e7-932b-eb7e5d85243d.png">

What happens when the promotion gets created is this --- look at the "Base code" field in particular:

<img width="1280" alt="screen shot 2017-04-03 at 6 45 07 pm" src="https://cloud.githubusercontent.com/assets/2460418/24638558/3e2f336a-189e-11e7-8f5f-d492fac29100.png">

Namely, a random string is appended to the end of my code. Is this expected behavior?

Furthermore, I cannot edit the "Base code" or the "Number of codes." In fact, I cannot even insert a cursor into these fields, as they are rendered `readonly`. I also cannot add any other codes (presumably it expects there to be 11 more?).

Is this a bug, or am I simply misunderstanding how to create a new promotion?

Thanks!

**Comment by jhawthorn** [comment]
This is all expected behaviour, but the UI was really bad. Fields are indeed supposed to be readonly once created. The random string is because you've asked it to create 12 codes, so it invokes the code generator (codes need to be unique). If you want to specify the exact code, number of codes needs to be `1` (I know this isn't obvious). 

This wasn't great, but I think it's greatly improved in #1509. At least what is being created is obvious, I think we can still do a better job of showing what codes have been created.

**Comment by bbuchalter** [comment]
> This is all expected behaviour

I have to say I think the inability to add more codes to an existing promotion is a major shortcoming. Is there an existing issue to request this feature? If not, perhaps this is where it belongs?
