### ISSUE TITLE
undefined method `currency' for nil:NilClass

### ISSUE THREAD

**Issue by robinboening** [solidusio/solidus#1859]
### Steps to reproduce
1. Create a new product
1. Go to `/admin/products/xyz/prices`
2. Change the currency of master variant
3. Go to `/admin/products/xyz/edit`

### Expected behavior
I should be able to render the edit form of the product without an error and see the new currency in the `Master Price` input field.

### Actual behavior
A 500 Error is raised with following backtrace
```
ActionView::Template::Error (undefined method `currency' for nil:NilClass):
    33:         <%= f.field_container :price do %>
    34:           <%= f.label :price, class: 'required' %>
    35:           <% byebug %>
    36:           <%= render "spree/admin/shared/number_with_currency", f: f, amount_attr: :price, currency: @product.find_or_build_master.default_price.currency %>
    37:           <%= f.error_message_on :price %>
    38:         <% end %>
    39:       </div>

/Users/robin/.rvm/gems/ruby-2.3.0/bundler/gems/solidus-322a83962e8a/backend/app/views/spree/admin/products/_form.html.erb:36:in `block in _c7429533764a4ba0490aeec7973f50dc'
actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `capture'
/Users/robin/.rvm/gems/ruby-2.3.0/bundler/gems/solidus-322a83962e8a/backend/app/helpers/spree/admin/base_helper.rb:10:in `field_container'
/Users/robin/.rvm/gems/ruby-2.3.0/bundler/gems/solidus-322a83962e8a/backend/config/initializers/form_builder.rb:6:in `field_container'
/Users/robin/.rvm/gems/ruby-2.3.0/bundler/gems/solidus-322a83962e8a/backend/app/views/spree/admin/products/_form.html.erb:33:in `_c7429533764a4ba0490aeec7973f50dc'
actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.2) lib/action_view/template.rb:157:in `render'
deface (1.2.0) lib/deface/action_view_extensions.rb:41:in `render'
...
```

### System configuration
**Solidus Version**: "2.3.0.alpha"

**Extensions in use**: None

**Comment by softr8** [comment]
The problem happens when the product does not have `Spree::Config.default_pricing_options.currency` in its [prices](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/price.rb#L25), not sure if the fix would be preventing users to update the currency in `/admin/products/xyz/prices/xx/edit` or add an extra flag to prices list specifying which one is the default, what do you think @mamhoff @jhawthorn ?

**Comment by mamhoff** [comment]
@softr8 We used to have an `is_default` boolean on prices that we removed because it was not clear what kind of `default` that would mean. 

The master price is defined to be of the configured default currency for admins. If that price is empty, the form should still render with the default currency, and an empty master price.
