### ISSUE TITLE
Extracting Spree::ProductProperty.value into Spree::PropertyValue

### ISSUE THREAD

**Issue by AndreiMotinga** [solidusio/solidus#1874]
### Steps to reproduce
Morning guys. 
[Here's a pretty much default solidus app with solidus_globalized installed and working
](https://am-solidus-default-store.herokuapp.com/)
[code here](https://github.com/AndreiMotinga/am-solidus-default-store)
You can login with default solidus credentials, admin@example.com and test123

Currently, we can create translations. Products, Taxonomies, etc work ok. 
Except for product properties.  
Currently, when we create `Spree::ProductProperty` we store `product_id`, `property_id`, and `value` (string) on it. In order to translate value, we create translation not for value itself but for `Spree::ProductProperty`. 

This leads to a lot of duplication.  In order to fix it, we could store `product_id`, `property_id` and `value_id` on `Spree::ProductProperty`, translate properties and values and only assemble them as needed. 
We have `Spree::PropertyType`, `Spree::PropetyValue` seems to fall in place pretty organically. 

I'm currently building a store, that sells construction tools, and there are a lot of products that are very similar, but not quite the same.  Having a bunch of properties on products seems like a more suitable solution here than option types and values.  Plus, this will allow creation of product comparing tables. 

I assume this could be done in solidus_globalize, but any other translation gem should face the same issue, so it seems like it could be better done in core. 

What do you think?

**Comment by AndreiMotinga** [comment]
So it's been 2 days, any reflection on this?

**Comment by AndreiMotinga** [comment]
:)

**Comment by alepore** [comment]
Hi, thanks for your contribution!

First of all, this will need some discussions about if/how/where to do this thing, so if you urgently need this on your project, please implement it on your codebase.

So the issue is: if you have thousand of products with a property like `Color => white`, you translate "Color" once, and "white" thousand of times. Right?
This actually makes sense if you think at the product property like a field of the product itself, like the description. 
Some stores may also have lots of products with the same description, would you merge them?

But this is not ideal in your situation, i understand it.
In my opinion the whole properties management is not perfect, because Property types are matched by their name in the main language.
This wasn't probably designed with translations in mind.

Extracting property values will lead to another situation when we match objects by a string value in some language, that can be very long, and can change, so i'm not really comfortable with this solution.
