### ISSUE TITLE
Missing partial for store credits in admin.

### ISSUE THREAD

**Issue by adammathys** [solidusio/solidus#193]
Should add something at `spree/admin/payments/source_views/_storecredit` otherwise store credit payments will result in server errors when viewing them in the admin.

**Comment by athal7** [comment]
the code does not support the ability to add store credits via admin, it is only designed to work with auto-adding of store credit.

**Comment by adammathys** [comment]
That view isn't associated with adding store credits. Right now, any store credit payments on an order have a link that results in a exception due to it trying to render information about the store credit but not finding an appropriate partial.

**Comment by athal7** [comment]
ah my mistake

**Comment by jhawthorn** [comment]
I was running into this again, have created #224 to fix it.

**Comment by cbrunsdon** [comment]
someone in slack reported this is still an issue, investigating now.

**Comment by joelind** [comment]
I'm seeing this now, with 1.3.0...Any updates?

**Comment by joelind** [comment]
Actually, the view my solidus admin is looking for is in *source_forms*, not *source_views*...

```
ActionView::MissingTemplate in Spree::Admin::Payments#new
Showing /Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_backend-1.3.0/app/views/spree/admin/payments/_form.html.erb where line #28 raised:

Missing partial spree/admin/payments/source_forms/_storecredit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :slim, :rabl], :versions=>[:v1]}. Searched in:
  * "/Users/joelind/projects/rockets/quark/app/views"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_gateway-1.0.1/lib/views/backend"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_backend-1.3.0/app/views"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_api-1.3.0/app/views"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_core-1.3.0/app/views"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kaminari-0.17.0/app/views"
  * "/Users/joelind/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.1.1/app/views"
```

**Comment by dangerdogz** [comment]
@joelind : The issue you have is a bit different. By default when you seed the store, Store Credit is added as a payment method with a display value of none [see the class] (https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/db/default/spree/store_credit.rb) so it's not supposed to show as an option when you reach Payments#new or if you checkout from the frontend since the store credit are applied automatically (which is also something to improve upon)

Currently, it's not "possible" to add store credit payments from the admin so the partial is missing because the feature is not implemented. I assume you updated the display value for it to show but it's not working as you reported.

Currently doing some preliminary work on this, in the meantime to restore the original behavior I suggest you update the StoreCredit payment method to "display_on: none"

**Comment by Sinetheta** [comment]
@dangerdogz what makes this funny is that `:none` is not included in `Spree::PaymentMethod::DISPLAY`, so it's not really a valid option, which means that if anyone ever clicks "update" in a store credit payment method they will unwittingly set the value to `:both`.

So I don't suspect that anyone running into this problem ever changed the value intentionally, and they certainly don't have an easy way to change it back.
