### ISSUE TITLE
Table rows should be consistent height

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#2028]
On the store stock page, there's a table with multiple height table cells. 
All table cells should be the same height across a row.
<img width="1014" alt="screen shot 2017-06-16 at 10 54 30 am" src="https://user-images.githubusercontent.com/15271353/27238592-63f44112-5282-11e7-97ce-d5d256d2d592.png">

**Comment by tvdeyen** [comment]
Yes. There is some very weird table markup going on. Have a branch laying around that fixes some of these issues. We publish it soon.

**Comment by samdking** [comment]
Hi, I have this same problem. Could you refer me to the branch you mentioned @tvdeyen? Is there any plan to merge this into a release?

**Comment by tvdeyen** [comment]
I did not have published a branch yet because @graygilmore volunteered to continue working on this particular area. This whole page needs a serious and well thought overhaul. My solution was more like a hotfix. Mainly I calculated the row height by the count of stock locations. This is a weak solution and we decided to not merge this.

**Comment by graygilmore** [comment]
Yes, the markup on this page is nothing short of a nightmare. I haven't dug into this area much further, to be honest. I think it needs a completely fresh solution.

**Comment by aitbw** [comment]
Fixed via #2862, @kennyadsl

**Comment by tvdeyen** [comment]
Yes
