### ISSUE TITLE
Canceled orders in `complete` scope

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#2099]
We have been experimenting with allowing users to cancel completed orders if they haven’t been fulfilled yet, and one of the things that has stood out to me as unintuitive is that the `Order.complete` scope includes cancelled orders.

This makes sense in the context of the admin `Orders#index` page, where it is useful for backend administrators to see canceled as well as completed orders, but it causes problems elsewhere.

For instance, the Sales Total report will still include revenue from canceled orders. This seems incorrect.

My proposal here would be to do something like the following:

1. change the `Order.complete` scope to include the additional restriction of `.where.not(status: 'canceled')` by default
2. create an `Order.canceled` scope to have a canonical way to select canceled orders (presumably it would just check for `status: 'canceled'` but maybe we also want to check for `.not(completed_at: nil)` or something)
3. create an `Order.complete.with_canceled` or `Order.complete_with_canceled` to include both fully completed orders as well as canceled ones. I see this mostly being useful on the backend in views like `Orders#index`.

If the above (or some variation on the above) seems like a useful approach to the Solidus team / community, let me know and I am more than happy to prepare a PR.

**Comment by bbuchalter** [comment]
Hey @brchristian - you raise an interesting point. Thanks for the issue submission. It's great to see you still hacking on this stuff; I remember when we did a bit of work together for `spree_tax_cloud` a long time ago.

Anyway, from my perspective, this issue is mostly one of semantics. From a certain perspective, for an order to be canceled, it must have be _complete_. If you only want to find orders that are completed and not canceled, there is a `by_state` scope you can use to accomplish what you've suggested in your second proposal.

As for the issue with the Sales Report, I think that's a very reasonable fix that would deserve it's own issue and a PR would likely be very welcome.

Just my two cents.

**Comment by brchristian** [comment]
@bbuchalter Agreed that it’s a semantics issue!

As you say, yes, the alternative and more minimal fix is just a PR to restrict the default Sales Total scoping in the Reports controller.

I can see the argument in either direction and am happy to go wherever majority opinion lies. Curious to kind of take the temperature of the community here and see what people think makes most sense.

**Comment by brchristian** [comment]
Closing here and linking to the recent discussion at https://github.com/solidusio/solidus/pull/2131
