### ISSUE TITLE
Cannot access order created via sandbox

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#2103]
### Steps to reproduce

From master:

```
rake sandbox
cd sandbox
rails console
```

### Expected behavior

```
Spree::Order.last.shipments.size
=> 1
```

### Actual behavior

```
Spree::Order.last.shipments.size
=> 2
```

(the last one has `stock_location_id: nil`)

**Comment by jhawthorn** [comment]
I ran a git bisect and found this was introduced by #1770 (so not an issue in 2.3.0).

The issue seems to come from [db/samples/reimbursements.rb](https://github.com/solidusio/solidus/blob/master/sample/db/samples/reimbursements.rb#L9-L11)

``` ruby
return_item.exchange_variant = return_item.eligible_exchange_variants.last
return_item.build_exchange_inventory_unit
return_item.accept!
```

`build_exchange_inventory_unit` builds a new inventory unit and a new shipment. When `accept!` is called that shipment is saved.

**Comment by jhawthorn** [comment]
Aha! I think this is because 
[in ReturnItem#build_exchange_inventory_unit](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/return_item.rb#L184), we initialize an `InventoryUnit` with an order, which is now a `has_many through: :shipment`, so it will create an empty shipment (believing it to be a join model).

**Comment by kennyadsl** [comment]
Yes, I think you are right. I was looking at the [`touch: true` into the association between shipment and inventory unit](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/inventory_unit.rb#L10) but your intuition seems to be the right way. I think we also need to pass the shipment when building that `InventoryUnit`. I'm not sure if the shipment should be the same as the current `inventory_unit` though.

**Comment by jhawthorn** [comment]
Closing this as #1770 has been reverted (for now)
