### ISSUE TITLE
Error including Spree::UserAddress in User Model

### ISSUE THREAD

**Issue by Ray1987** [solidusio/solidus#2267]
### Steps to reproduce
1. Followed the instructions to link the solidus user to an own User model: 
https://guides.spreecommerce.org/developer/authentication.html

2. Added this into the user model:
  include Spree::UserMethods
  include Spree::UserAddress -> causing the error 
  include Spree::UserPaymentSource

### Actual behavior
Error: "user.rb:4:in `include': wrong argument type Class (expected Module) (TypeError)"

### System configuration
**Solidus Version**:
solidus (2.3.0)
solidus_api (2.3.0)
solidus_auth_devise (2.0.0)
solidus_backend (2.3.0)
solidus_core (2.3.0)
solidus_frontend (2.3.0)
solidus_sample (2.3.0)
solidus_support (0.1.5)

**Extensions in use**:
gem 'solidus'
gem 'solidus_auth_devise'

**Comment by jhawthorn** [comment]
We're working on having good and modern documentation for Solidus, unfortunately the old Spree docs aren't good or accurate (for either project).

Instead of including individual modules which Solidus would require for correct functioning, there is a single module, [Spree::UserMethods](https://github.com/solidusio/solidus/blob/master/core/app/models/concerns/spree/user_methods.rb) which a user model is expected to include.
