### ISSUE TITLE
discussion: why only a generic way to register order event hooks ?

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2296]
Hi, when people register hooks to trigger custom actions on order events, there is only a general way to register hooks 
```
Spree::Order#register_update_hook
```
Is there a reason why there isn't more specific way to register new actions ? 
Wouldn't it be better to have more specific hooks on each events so that users that don't know the code so well can plug in custom actions more easily ? 
I won't list all but, as an example, I think about hooks like:

```
Spree::Order#register_on_add_product_to_cart_hook
Spree::Order#register_after_complete_hook
Spree::Order#register_before_complete_hook
Spree::Order#register_after_payment_hook
Spree::Order#register_before_payment_hook
etc...
```

For example and as a side note, in our case, it wasn't that easy to find how to trigger an action exactely once when it is completed and fully paid.
The easiest way we found was to look into the state_changes table... (and it seems wrong to use the content of that "notification" table for calculation logic to me).

**Comment by jhawthorn** [comment]
Hi @loicginoux, discussions are better for our `#solidus` slack channel.

This is a very good question and an area we are looking to improve. It is too hard for developers to add logic to trigger at the right time. However I believe this is deceptively difficult to do in a good way.

I think we haven't added these already because adding hooks/callbacks has been a pretty brittle and unsuccessful way to add extensibility. (I'd actually really like to remove the orders' update_hooks, which are very problematic because of how often they run)

The main problem is anticipating what a user expects to be able to do within any of these hooks and ensuring the surrounding code behaves correctly. Let's take your first example, `register_on_add_product_to_cart_hook`. What should a user be able to do here?

Say a hook modifies the line item's price in some way, that would mean we'd have to run `order.recalculate` _after_ the hooks to ensure the order took the price into account. Another hook might want to log the new state of the order somewhere, and that would have to happen after an `order.recalculate`. This isn't even really solved by splitting into `before_`/`after_` hooks, as you can't modify a line_item before it exists.

This is why we've preferred to introduce extension points with a specific function, which return data Solidus acts on instead of modifying data, like the pluggable [PriceSelector](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/variant/price_selector.rb) class.

It's possible we could introduce these with a warning that developers shouldn't modify any of Solidus's records during a hook (but I would guess this is one of the main desires of these hooks).

> For example and as a side note, in our case, it wasn't that easy to find how to trigger an action exactely once when it is completed and fully paid.

I think this is desirable for a lot of stores, and it would be nice to have something better, but there are caveats. This might happen several times to the same order. Consider a customer calling in and asking for an item to be added to their order: the order will have started complete and fully paid, leave that state as a new item is added, and then re-enter it again as the new total is paid for. Refunding a user for any reason also raises questions about whether this should be called.


There aren't easy solutions, but this is a discussion I and I'm sure other would be happy to continue in slack.
