### ISSUE TITLE
Integrating with RefineryCMS

### ISSUE THREAD

**Issue by Segellion** [solidusio/solidus#2373]
### Steps to reproduce
How can we make this happen

1. Install RefineryCMS
2. Add solidus (as instructed within the documentation) to gemfile.
3. Perform "bundle"
4. Error message:
Bundler could not find compatible versions for gem "stringex":
  In Gemfile:
refinerycms-acts-as-indexed (>= 3.0.0,  > 3.0) was resolved to 3.0.0, which
depends on
      stringex ( > 2.5.2)

    solidus ( > 2.4) was resolved to 2.4.0, which depends on
      solidus_core (= 2.4.0) was resolved to 2.4.0, which depends on
        stringex ( > 1.5.1)

### Expected behavior
I'm hoping these two gems can work in tandem.

### Actual behavior
I am unable to install the solidus gem.

### System configuration
**Solidus Version**:

2.4

**Extensions in use**:

RefineryCMS 4.0
refinerycms-acts-as-indexed 3.0
refinerycms-wymeditor 2.0
refinerycms-authentication-devise 2.0

**Comment by dhonig** [comment]
We will be glad to help you with this one:
 https://github.com/AlchemyCMS/alchemy-solidus

Not sure of the state of refinery.

**Comment by OrbitalAgility** [comment]
I'm not sure if that's compatible? I work through installing alchemy, to come to this error after adding alchemy-solidus to my gemfile:

Bundler could not find compatible versions for gem "alchemy_cms":
  In snapshot (Gemfile.lock):
    alchemy_cms (= 4.1.0.beta)

  In Gemfile:
    alchemy_cms

    alchemy-devise was resolved to 4.1.0.beta, which depends on
      alchemy_cms (< 4.99, >= 4.0.0.beta)

    alchemy-solidus was resolved to 1.0.0, which depends on
      alchemy_cms (~> 3.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by ccarruitero** [comment]
Seems to be incompatible dependencies between latests `alchemy-devise` and `alchemy-solidus`. There is a [PR](https://github.com/AlchemyCMS/alchemy-solidus/pull/15) in progress for fix that in `alchemy-solidus`.

I recommend you to use another version of `alchemy-devise` that be compatible or use `alchemy-solidus` from the PR that fix the dependency until be merged.

Another option is to use `solidus_auth_devise` instead `alchemy-devise`

**Comment by mtomov** [comment]
Correct that - `solidus_auth_devise` is usually used for user authentication instead of the `alchemy-devise` gem.

**Comment by OrbitalAgility** [comment]
I'm currently trying to get static pages working with Solidus. Maybe alchemy isn't the best choice? I can't get it to work. But there is a gem for Solidus static pages... which also seems to use deprecated libraries.

solidus_static_content was resolved to 1.0.0, which depends on
      deface (~> 1.0.2)

Am I going about this all wrong? I have spent the past two days juggling between deprecated gems.

**Comment by cbrunsdon** [comment]
We only barely use stringex in core, I bet we could bump it pretty safely (to fix the original dependency problem), or relax the requirement to allow 2.x if that works as well.

I also see no reason to not relax the deface requirement in solidus_static_content as well.

**Comment by bricesanchez** [comment]
@dhonig It's better to ask the Refinery team to be sure of the state. To answer you, the CMS is going well, thanks :)

 > I'm currently trying to get static pages working with Solidus.

If you only need static pages, you don't need a CMS, you could just use `solidus_static_content` or `high_voltage` gems

If you still need a CMS, feel free to try Refinery or Alchemy both have great features depending your needs and have a solidus authentication connector

**Comment by OrbitalAgility** [comment]
Because I could not get a CMS running with Solidus, I attempted to use the solidus_static_content gem. Which is is unable to install due to deface being outdated. I had posted my attempt earlier. but this is the error I receive when I attempt to install solidus_static_content:

solidus_static_content was resolved to 1.0.0, which depends on
deface (~> 1.0.2)

**Comment by bricesanchez** [comment]
@OrbitalAgility You could temporarily remove `refinerycms-acts-as-indexed` from your Gemfile and get Refinery running with Solidus, i've write a guide for Spree but it could be very similar for Solidus: http://www.brice-sanchez.com/5-easy-steps-to-use-refinery-cms-and-spree-e-commerce-on-the-same-ruby-on-rails-application/

**Comment by OrbitalAgility** [comment]
I'm sorry, i've deviated from the original topic of this thread. I'm no longer working with refineryCMS because I figured the solidus_static_content gem would be easier.

I have since managed to get it running (albeit the documentation is out of date and needs an update)

My rails instance is running again! Although I get the following error displayed in my browser when I hit localhost:

PG::UndefinedTable: ERROR: relation "spree_pages" does not exist LINE 8: WHERE a.attrelid = '"spree_pages"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod, c.collname, col_description(a.attrelid, a.attnum) AS comment FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum LEFT JOIN pg_type t ON a.atttypid = t.oid LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation WHERE a.attrelid = '"spree_pages"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

**Comment by swcraig** [comment]
There is a [PR open to remove stringex](https://github.com/solidusio/solidus/pull/2383) if that is what we want to do.

**Comment by askl56** [comment]
Given that PR has been merged, can this be closed?

**Comment by jarednorman** [comment]
We can close this!
