### ISSUE TITLE
Unauthorized redirections fail on Solidus engines mounted with namespace

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#2692]
When Solidus routes are mounted with a custom namespace, for example:

```mount Spree::Core::Engine, at: '/shop'```

then the app frontend redirects to `/unauthotized` instead of `/shop/unauthorized`. 
Tested with Solidus master branch.

**Comment by kennyadsl** [comment]
Closing this since this should be changed in the auth system as done in [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise/blob/01459b4339b0130241886bbcc3b35af1853f1e74/lib/spree/auth/engine.rb#L58-L67), as suggested in the [related PR](https://github.com/solidusio/solidus/pull/2693).
