### ISSUE TITLE
Not update available on date

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2721]
### Steps to reproduce
In products show a different date in input datapicker field that in database
![image](https://user-images.githubusercontent.com/24247266/39479469-9c87fcb0-4d65-11e8-8194-458574a6f440.png)

### System configuration
**Solidus Master last version**

**Comment by jtapia** [comment]
Hi, are you using translations?

**Comment by jacobherrington** [comment]
Hey @sechix I can't replicate this issue, it seems to be working for me. 

If you hit update at the bottom of the product page, does your database match?

Could you post some reproduction steps?

Thanks!

**Comment by sechix** [comment]
![image](https://user-images.githubusercontent.com/24247266/41254387-996aef64-6dc3-11e8-8cdd-854979d8da11.png)


Update product:
![image](https://user-images.githubusercontent.com/24247266/41254415-a96e8bc8-6dc3-11e8-9d9a-109379116e45.png)

After update (even refreshing page):

![image](https://user-images.githubusercontent.com/24247266/41254452-cb241940-6dc3-11e8-9a95-cc00fd196eba.png)

**Comment by jtapia** [comment]
with `es-MX` you can see this:
![screen shot 2018-06-13 at 11 40 43 am](https://user-images.githubusercontent.com/957520/41370131-69e800d4-6f0c-11e8-9cca-d9668b4eb0c8.png)

and later I got a `missing translation` error, I created this PR https://github.com/solidusio/solidus_i18n/pull/129 to fix that, with `es, es-EC and es-CL` is working fine

**Comment by Draiken** [comment]
I have the same issue. Seems to be related to localization since I use pt-BR and have the exact same issue. My guess is that the datepicker format has a specific format and i18n changes the default date formats, causing the disconnect between the actual value from the input and the datepicker's display

**Comment by Draiken** [comment]
To expand a bit: on the context of solidus_i18n you see a field called `spree.date_picker.format` and it makes sense to localize that to the local format. However by doing that you break the datepickers on the admin (haven't tested others, but I imagine everywhere that this helper is used will do that).

I propose we hard-code the datepicker format to something that always works, since this is not a presentational value but instead a value that is used by a third party library.
