### ISSUE TITLE
Versions up to 2.2 depend on a vulnerable version of paperclip

### ISSUE THREAD

**Issue by shkrt** [solidusio/solidus#2790]
Solidus-core up to version 2.2 depends on a vulnerable version of paperclip gem, the vulnerability itself is described in https://nvd.nist.gov/vuln/detail/CVE-2017-0889. Can we relax paperclip version constraint for 2.0, 2.1 versions as it is done for 2.2?

**Comment by kennyadsl** [comment]
I think we can close this issue since we should be fine on 2.2 which is within the supported timeframe:


- 2.0: [`'paperclip', '~> 4.2'`](https://github.com/solidusio/solidus/blob/v2.0/core/solidus_core.gemspec#L32)
- 2.1: [`'paperclip', '~> 4.2'`](https://github.com/solidusio/solidus/blob/v2.1/core/solidus_core.gemspec#L33)
- 2.2: [`'paperclip', ['>= 4.2', '< 6']`](https://github.com/solidusio/solidus/blob/v2.2/core/solidus_core.gemspec#L33)

If users need older versions and they don't want to upgrade Solidus, they can just fork and use their own repo since those versions will not change anymore in the future. 

Thanks and sorry for taking too long to answer.

**Comment by kennyadsl** [comment]
I think we can close this issue since we should be fine on 2.2 which is within the supported timeframe:


- 2.0: [`'paperclip', '~> 4.2'`](https://github.com/solidusio/solidus/blob/v2.0/core/solidus_core.gemspec#L32)
- 2.1: [`'paperclip', '~> 4.2'`](https://github.com/solidusio/solidus/blob/v2.1/core/solidus_core.gemspec#L33)
- 2.2: [`'paperclip', ['>= 4.2', '< 6']`](https://github.com/solidusio/solidus/blob/v2.2/core/solidus_core.gemspec#L33)

If users need older versions and they don't want to upgrade Solidus, they can just fork and use their own repo since those versions will not change anymore in the future. 

Thanks and sorry for taking too long to answer.
