### ISSUE TITLE
Crazy Request

### ISSUE THREAD

**Issue by tesserakt** [solidusio/solidus#285]
Make Solidus use only immutable data structures, perhaps using hamster? This would in the long run help to eliminate a whole class of bugs, even if it creates some short term pain.

**Comment by jhawthorn** [comment]
We're not looking into immutability at a data-structure level. It is, however, a nice ideal to look for when designing/writing/reviewing code.

In another PR we are making Addresses immutable, so that they can be shared between orders. Cartons were designed in a similar mindset, we didn't want to mutate shipments in order to show how items actually made it out the door.

**Comment by tesserakt** [comment]
@jhawthorn so you would be open to slowly changing the codebase to all-immutable through subsequent PRs? Or are you saying it is out altogether?

**Comment by athal7** [comment]
From my perspective, we would be open to adding immutability for use cases where it makes sense for the model to be immutable, not just for the sake of immutability.

**Comment by jhawthorn** [comment]
@tesserakt I don't expect to see an all-immutable codebase, but if small changes result better code, we'll absolutely accept it. We do however need to maintain compatibility. Using hamster is out, as we aren't writing heavily threaded code with sharing.

I think if we had unlimited time and no existing installations to worry about Andrew, Clarke, Greg and I would be rewriting this totally immutable in elixir :P.

**Comment by tesserakt** [comment]
Point taken :) I just found out how much solidus is willing to break with the past. So in solidus, backwards compat >  rearchitecting in cases where they conflict.

**Comment by athal7** [comment]
@tesserakt not necessarily, as long as there's a clean upgrade path
