### ISSUE TITLE
Misaligned table on the Stock page

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2857]
This is a small UI bug on the Stock page. Stock Location, Back orderable, Count on Hand are all aligned incorrectly, this is because these td elements are wrapped in tr instead of being inside the same tr as the other elements on the row. 

![image](https://user-images.githubusercontent.com/11466782/45922624-02233100-be97-11e8-9b19-e9f92be8c8fc.png)

**Comment by jacobherrington** [comment]
I am working on this, but happy to work with anyone who'd like to contribute!

**Comment by jacobherrington** [comment]
Just found #2028. @tvdeyen do you still have some work for this?

**Comment by jacobherrington** [comment]
How do you feel about rebuilding this using CSS (backend already has Bootstrap's grid) instead of a table?

**Comment by tvdeyen** [comment]
I would even prefer that, but we would need to have some kind of visual guidance (ie. by a UI/UX person) for this, as this would be the first time that we introduce another way of displaying tabular data in Solidus backend and I would like to "do it right" instead of rush things in. We spent a lot of time into refining the backend we inherited from Spree 2.4. I don't want this new interface to look misplaced.

I can make a proposal. Let's see what the others think about it.

**Comment by tvdeyen** [comment]
This is what I have so far:

1. Modify stock instead of setting it's absolute vaule
2. Nested stock location stock items table

![solidus test_admin_stock_items_utf8 e2 9c 93 stock_location_id variant_search_term button laptop with hidpi screen](https://user-images.githubusercontent.com/42868/45930504-72968480-bf61-11e8-9b74-bd760b41fcd2.png)

Better than I remember it would be. WDYT?

There are some specs pending, though.

**Comment by jacobherrington** [comment]
I think that looks great. I think having to hack around with tables is a pain, but making this change would definitely be a gain.

**Comment by tvdeyen** [comment]
@jacobherrington #2862 is now ready for review
