### ISSUE TITLE
Local solidus with overwrites?

### ISSUE THREAD

**Issue by kubet** [solidusio/solidus#3107]
Hi, how can I see a local version of a solidus? I installed 'solidus_auth_devise' and I was looking solidus GitHub for reference but 

> spree/shared/_login_bar_items.html.erb

 is empty. Are there any versions that have overwrites applied?

**Comment by kennyadsl** [comment]
Hey there, you can just check this file: https://github.com/solidusio/solidus_auth_devise/blob/91687769600cc9292e198684be8d15b6796f07e2/lib/views/frontend/spree/shared/_login_bar_items.html.erb

Views are there since they are loaded conditionally if you have loaded specific parts of solidus (frontend, backend, api).
