### ISSUE TITLE
RFC: Remove firstname and lastname from adresses

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus#3234]
## The problem

Names :)

Seriously, read https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

Also issues like https://github.com/solidusio/solidus_paypal_braintree/issues/226 happen

## The proposal

We should add a `name` column to `Spree::Address` then deprecate and later remove `firstname` and `lastname`.

**Comment by ericsaupe** [comment]
I'm all for this. It simplifies a lot of the edge cases surrounding names and how to display them. I can see use cases where they want a bit more of a restricted naming experience a gem can be created to handle those cases.

**Comment by jacobherrington** [comment]
I have nothing against this -- I think it's a great change.

**Comment by kennyadsl** [comment]
I also in favor of this.

**Comment by skukx** [comment]
Here Here

**Comment by filippoliverani** [comment]
I really like this change and I started to work on it in #3447 but with the help of @kennyadsl I realized it was too much for a single PR.

I'm tring to split the work into four different steps: 
1. add `name` virtual attribute which still relies on `firstname` and `lastname` #3458 
2. use `name` in views e api responses instead of `lastname` and `firstname` if an ad hoc `show_address_deprecated_attributes` preference is set to `true`
3. add `name` column to Adress db table, add a rake data migration task and keep attributes in sync during updates
4. deprecate `show_address_deprecated_attributes` preference, `firstname`, `lastname` and `full_name`

What do you think?

**Comment by kennyadsl** [comment]
At the current stage we have 3 options:

Option 1:

Add a way to do: `address.update_attributes(name:)`. Now it's not possible since `name` is not a column in the database. We can override how rails sets attributes and split `name` into two db fields. 

Option 2:

Add `name` to the database and provide a fallback when `name` is not set. The job to migrate can be performed async.

Option 3:

Add `name` to the database and provide a migration/rake task that combines all the old `firstname` and `lastname` into `name. Can take forever on old stores with a lot of records.

**Comment by kennyadsl** [comment]
We discussed this during the core team, we'd go with option 2 (adding a fallback when `name` is not present) and creating a migration that has multiple options and each store can select the best one based on their needs. We did something similar [here](https://github.com/solidusio/solidus/blob/9864746a3b5d8493f990ef63b28e4989f6534673/core/db/migrate/20190106184413_remove_code_from_spree_promotions.rb) that we can replicate.

The handlers we were thinking of are:
- `RaiseException` (default): it will tell people that this thing needs their attention.
- `MigrateData`: it combines `firstname` and `lastname` (with SQL?) and moves the result into `name`.
- `DoNothing`: it allows people to keep the current database structure, they can re-add `firstname` and `lastname` in the codebase to keep using the old way of setting names or maybe they can execute the migration in the background later if they are worried about the migration to be too time-consuming for their database size.

**Comment by tvdeyen** [comment]
We might be able to help with the migration since we already done that for one of our clients. 

cc @mamhoff

**Comment by kennyadsl** [comment]
@tvdeyen that would be great, thanks!

**Comment by cmbaldwin** [comment]
What to do others do about third parties who haven't been persuaded as to the elegant and open-minded solution of a simple 'name' column?

https://twitter.com/codybaldwin/status/1602112595129151488
