### ISSUE TITLE
No minimum ruby version is specified

### ISSUE THREAD

**Issue by softr8** [solidusio/solidus#3302]
Looking at https://extensions.solidus.io, some of them are in red in the latest Solidus Version (2.9) and master, the main reason is that this change https://github.com/solidusio/solidus/commit/707e79b4e921e06d8b3c2fa7b2a9ead9fe2500bc  uses a method `finite?` that was introduced in Ruby 2.4, but the extensions are being tested using an older version of Ruby

**Solidus Version**:
2.9 master

**To Reproduce**
Try to run solidus 2.9 or master using an older version of ruby than 2.4 then perform any API call that renders a product object

**Current behavior**
It raises an error saying that undefined method `finite?' for Fixnum

**Expected behavior**
Not sure, maybe send a warning about minimum ruby version needed

**Comment by kennyadsl** [comment]
At the moment [Rails 6 requires Ruby >= 2.5](https://github.com/rails/rails/blob/6b40767df8635125c62b550d2652074d2e6daf03/rails.gemspec#L12) while [Rails 5.2.x supports Ruby >= 2.2.1](https://rubygems.org/gems/rails/versions/5.2.3). 

I'm not sure what's the best thing to do here considering Ruby 2.3 is EOL now and 2.4 will go EOL soon. 

I think that to be in sync with Rails (supporting Ruby >= 2.5) could be a good solution here but I'd like to have more feedback from the community. Is this something that could break your stores for some reason?

**Comment by kennyadsl** [comment]
It looks like this has already been discussed and I totally forgot https://github.com/solidusio/solidus/pull/2794. 😱 

Well, if we still want to keep support for Ruby 2.2, we'd need to change that commit and avoid using `finite?`, remove all `&.` usage we introduced so far and backport changes to Solidus `v2.9.x`.

We'll discuss this in the next Core Team meeting and I'll report back. Any feedback from the community is appreciated in the meantime.

**Comment by mdesantis** [comment]
I think the minimum Ruby version should be at least limited by Ruby EOL. It doesn't make sense to me to support an EOL'd Ruby version.

**Comment by kennyadsl** [comment]
@mdesantis I agree, e-commerce applications (and probably also other applications) should not run on Ruby versions that do not receive security patches but I don't want to exclude people blocked on some old Ruby version at the same time.

**Comment by tvdeyen** [comment]
> but I don't want to exclude people blocked on some old Ruby version at the same time.

Yes. We should not make this decision for our users. There are several reasons (other dependencies, server constraints) why people cannot immediately update the Ruby version.

The same is true for dependency versions. We should always take the lowest boundary that our code base is compatible with. If our code works with Ruby 2.0 we should not raise it’s minimum version just because we think it’s right.

We develop a library that is used inside a rails app that has many other dependencies and constraints we don’t have control over. That’s why we need to be much more loose in our constraints.

**Comment by tvdeyen** [comment]
> I think the minimum Ruby version should be at least limited by Ruby EOL. It doesn't make sense to me to support an EOL'd Ruby version.

That’s not the right thing to do from a Library standpoint. We need to set the Ruby version constraint to the minimum Ruby version our code is working with. The EOL of Ruby version has nothing to do with this decision. This is a decision store owners do.

**Comment by tvdeyen** [comment]
Yes. I agree and since the Rails gem handles this constraint for us we don’t need to add one ourself (beside the one we need for our syntax). Bundler will handle this for us. I don’t want to update our required Ruby version every time a gem decides to not support an old version of Ruby anymore. Since this gem is setting the constraint in their gemspec we good, no?

**Comment by tvdeyen** [comment]
Just to clarify. 

I don’t talk about running specs on old Ruby versions, when I say support old Ruby versions. I just think we should not constraint our gemspec overly strict.

**Comment by tvdeyen** [comment]
So, how to proceed, then?

I think if we still support Rails 5.2 we also need to support Ruby >= 2.2 and should remove the syntax that makes Ruby 2.4 our lowest supported version.

But in the other hand the safe navigation introduced in Ruby 2.3 is beneficial for us and the community. And Ruby 2.2 is EOL. So maybe our lowest supported Ruby version should be 2.3 although this violates the Rails 5.2 constraint? Are we actually using `&.` that much? 

Otherwise we would have to remove all usages of `&.` and replace it with `try` (meh) and back port these changes to how many versions? This doesn’t seem like a good choice either.

WDYT?

**Comment by skukx** [comment]
Be careful using `try` as it could silence `NoMethodError` in some cases:
See: https://apidock.com/rails/v3.2.1/Object/try#1533-In-Rails-4-it-DOES-return-nil-even-if-the-object-you-try-from-isn-t-nil

Shouldn't be a an issue, but something to be aware of.

**Comment by jarednorman** [comment]
Yeah, in Rails 4+ you pretty much always want `try!`, which just swallows `nil`-values, not `NoMethodError`.

**Comment by kennyadsl** [comment]
I'd like to also find a way to avoid the [mistake we (actually I) made](https://github.com/solidusio/solidus/pull/3210/files#diff-7044a491d77e88a7de05c5be11e7253dR188) introducing something that is not compatible with Ruby 2.2 without any Ci tool being able to catch this problem. This process is too fragile since it relies only on PR reviews from the Core Team and community (which are always welcome!). 

What about using the minimum Ruby version that we support (2.2 in this case) for running tests on the CI as well?

**Comment by tvdeyen** [comment]
> I'd like to also find a way to avoid the mistake we (actually I) made introducing something that is not compatible with Ruby 2.2 without any Ci tool being able to catch this problem. This process is too fragile since it relies only on PR reviews from the Core Team and community (which are always welcome!).

Rubocop has checks for that. We just need to set the `TargetRubyVersion`

> What about using the minimum Ruby version that we support (2.2 in this case) for running tests on the CI as well?

No, I don't think we need to test for EOL Ruby versions.

**Comment by kennyadsl** [comment]
> Rubocop has checks for that. We just need to set the TargetRubyVersion

But it didn't catch anything in https://github.com/solidusio/solidus/pull/3210, not sure if it's a HoundCI issue?

Anyway isn't odd to have the Rubocop `TargetRubyVersion` to 2.2 and perform tests against 2.5?

**Comment by mdesantis** [comment]
> Rubocop has checks for that. We just need to set the `TargetRubyVersion`

But Rubocop checks the syntax only, doesn't check if a spec passes or not; I think that a supported version should be added to the CI, because otherwise you can't really say whether it is supported, because features could be broken and you'll never know

**Comment by jacobherrington** [comment]
> Anyway isn't odd to have the Rubocop TargetRubyVersion to 2.2 and perform tests against 2.5?

This is a good point. 

> But Rubocop checks the syntax only, doesn't check if a spec passes or not; I think that a supported version should be added to the CI, because otherwise you can't really say whether it is supported, because features could be broken and you'll never know

This is a good point too.

Should we run tests against 2.2? I feel like that is the correct answer, if we really do support it.

**Comment by kennyadsl** [comment]
Other pieces to add to the puzzle: 

**Rubocop support**

They dropped 2.2 support. That's why [I upgraded TargetRubyVersion to 2.3](https://github.com/solidusio/solidus/pull/3256). That means that we should probably lock `rubocop` to an older version, and see how that work with HoundCI. 


**Ruby Usage Stats**

Not sure if this can be helpful but I found these JetBrain Ruby usage statistics: https://www.jetbrains.com/lp/devecosystem-2019/ruby/ . It looks like Ruby 2.2 could be used by 3% only.

**Comment by BenMorganIO** [comment]
But why test against a version we cannot support due to a dependency? It seems silly.

**Comment by jacobherrington** [comment]
@BenMorganIO I think we need to decide what we choose to support. Historically, we've tried to support the Ruby versions that Rails supports. I'm not sure what the right answer is now. We talked a bit about this in the core team meeting, but I do not know the correct answer personally.

**Comment by BenMorganIO** [comment]
Rails already made the decision for us. I find it a little redundant checking to see if you can support Ruby 2.4 when the app is built on a framework which will soon become >= 2.5.

**Comment by ericsaupe** [comment]
@BenMorganIO You're right, Rails 6 only supports Ruby 2.5.0 or greater. The question is do we support Ruby 2.2 on older versions of Solidus, that have not hit their EOL, that still support Rails 5 which requires 2.2.2 or newer.

**Comment by BenMorganIO** [comment]
The answer would be yes. People using Solidus, say, 2.0 would expect that when they do a patch or minor version update, their language version shouldn't change. Semantic version control has already established an implicit contract for this.

**Comment by kennyadsl** [comment]
We'd agree, but Rubocop [dropped 2.2 support](https://github.com/solidusio/solidus/issues/3302#issuecomment-528259209). Should we lock Rubocop to its last version that supports 2.2?

**Comment by BenMorganIO** [comment]
That sounds like a plan.

**Comment by kennyadsl** [comment]
In the last core team meeting we decided to go with:

- bump minimum required ruby version of master and v2.9 to `2.4`. If someone can't upgrade to latest Ruby, they cannot use latest Solidus. Still, they can use Solidus to older versions. 
- test all extensions with Ruby 2.5 for the sake of simplicity and avoid wasting core team and community members' time and CI resources creating a too complex matrix.
