### ISSUE TITLE
Removing extensions

### ISSUE THREAD

**Issue by Henrik41** [solidusio/solidus#3650]
I installed some extensions and I had a hard time removing them (it's not only the gem but also the migration, and the rest).  My suggestion:

1. Develop a guide on how to remove the extensions (I know how to remove the gem but extension might have generators).
2. Encourage developer to have a uninstall function (remove the migration, etc).

For example rollbacks are not always possible, how do you do it in these cases? etc

**Comment by jarednorman** [comment]
I think it will have to be documented on a per-extension basis, but this is generally a good idea.

**Comment by kennyadsl** [comment]
It's a good idea, even if removing data from a production database is too dangerous to be made by an automated script that works for everyone.

For "the rest" do you mean the assets references that the extension copy in your application? Even here, due to the solidus' nature, it's very hard to predict how people handled that but it's not dangerous to try to remove them if the happy-path has been used. I think that Rails generators already have some handy methods to remove specific lines from files.

**Comment by aldesantis** [comment]
Since extension installers are regular Rails generators, uninstalling an extension should usually be possible by "deleting" the corresponding generator, e.g.
```console
$ rails d solidus_stripe:install
```
This will reverse any actions originally performed by the installer. Of course, this may not always be possible to do automatically, since you may have modified those files in ways that make reverting the original action impossible.

As for the DB changes, there are two ways to do it, depending on your situation:

- If the extension you want to remove is already in production and/or you have applied other schema changes in the meantime, you may want to create new migrations that rollback the extension's original migrations.
- If you were just playing with the extension locally, you may simply rollback the migrations (as long as the migrations are all reversible, otherwise see the previous point).

As a rule of thumb, extension authors should also strive to make all of their migrations fully reversible.

**Comment by Henrik41** [comment]
Thanks for your comments. I think they are very helpful.
