### ISSUE TITLE
Not able to change images size 

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3700]
I am trying to change sizes with this in the initializer:
Spree::Image.attachment_definitions[:attachment][:styles] = {
  mini: '48x48>',
  small: '100x100>',
  product: '240x240>',
  large: '600x600>'
}
But 'module Spree::Image::ActiveStorageAttachment' don't take  new sizes. How to do it?

**Solidus Version**:
Last version of master

**To Reproduce**

**Comment by sechix** [comment]
Hi, any idea? @kennyadsl

**Comment by hefan** [comment]
It doesn't seem to work any longer with Rails 6 / Zeitwerk in an initializer. 
Somehow it gets overriden again with the default styles from `core/app/models/spree/image/paperclip_attachment.rb`.
To get it to work with Rails 6 you have to decorate Spree::Image an do something like
```
module ImageDecorator

  def self.prepended(base)
    base.attachment_definitions[:attachment][:styles] = {
      mini: '48x48>', small: '100x100>', product: '240x240>', large: '600x600>'
    }
  end

  Spree::Image.prepend self
end
```
For more details about Decorations: https://guides.solidus.io/developers/customizations/decorators.html

With Rails 5.2 it works fine

@kennyadsl i am not sure who to make it work again in Zeitwerk. Maybe you can suggest something?

**Comment by kennyadsl** [comment]
I think it's a filename issue. Where this `ImageDecorator` lives exactly?

**Comment by hefan** [comment]
The Image Decorator would be a workaround. Normally
```
Spree::Image.attachment_definitions[:attachment][:styles] = {
  mini: '48x48>',
  small: '100x100>',
  product: '240x240>',
  large: '600x600>'
}
```
should work in an initializer, which seems not to work in rails 6

**Comment by kennyadsl** [comment]
Oh, you are right. This seems like a bug then, I'll try to take a look asap.

**Comment by EduardoGHdez** [comment]
There is another workaround 

You are able to configure your own `image_attachment_module` from `Spree::Config` 😄 
https://github.com/nebulab/solidus/blob/master/core/lib/spree/app_configuration.rb#L477-L483

**Comment by nbelzer** [comment]
Given that this is tagged as a beginner friendly issue I decided to verify if the bug still exists (since the last update on this issue was 1,5 year ago at this point) before trying to resolve it. 

To update the `product_image_styles` I was able to use the following initializer snippet:
```ruby
Spree.config do |config|
  ...
  config.product_image_styles = {
    mini: '48x48>',
    small: '100x100>',
    product: '240x240>',
    large: '600x600>'
  }
  ...
end
```

This configuration option is used in `Spree::Image::PaperclipAttachment` and`Spree::Image::ActiveStorageAttachment`, of which by default the later is included in `Spree::Image` as `image_attachment_module` by default.  Lets focus on the `Spree::Image::ActiveStorageAttachment` first:

https://github.com/solidusio/solidus/blob/cc56661f4faa0c1cadbf979bef6fddbc53509e54/core/app/models/spree/image/active_storage_attachment.rb#L14-L16

The method `has_attachment` stems from `Spree::ActiveStorageAdapter`, the following snippet shows how calling `has_attachment` sets the `@attachment_definition` which is used in the `attachment_definitions` (note the plural name) method.

https://github.com/solidusio/solidus/blob/3ba6bc60f270b3a139ab56ab962f7ffedf7c2148/core/app/models/concerns/spree/active_storage_adapter.rb#L32-L46

Therefore by using the configuration snippet above you are able to customize the attachment styles, therefore there is no longer a need to override or patch the `attachment_definitions` method.  Looking at [the git blame for when the configuration option was introduced](https://github.com/solidusio/solidus/commit/b1fa1b897fc9eed74b2c5fe77f9b621c6e7daa2e), it seems that the author indeed meant to deprecate the need to override the `attachment_definitions`. 

Both [the developer guides](https://guides.solidus.io/developers/products-and-variants/product-images.html) and [edgeguides](https://edgeguides.solidus.io/advanced-solidus/images-and-image-processing) still recommend using the following snippets:
```ruby
# From the developer guides
Spree::Image.attachment_definitions[:attachment][:styles] = {
  mini: '48x48>',
  small: '100x100>',
  product: '240x240>',
  large: '600x600>'
}
```
```ruby
# From the EdgeGuides
module AmazingStore
  module Spree
    module Image
      module CustomizeSizes
        def self.prepended(klass)
          klass.attachment_definitions[:attachment][:styles] = {
            mini: '48x48>',
            small: '400x400>',
            product: '680x680>',
            large: '1200x1200>',
            jumbo: '1600x1600>'
          }
        end

        ::Spree::Image.prepend self
      end
    end
  end
end
```

As this is outdated, I recommend we use this issue to create a PR that updates the documentation accordingly, and adds some tests such that we verify this behaviour (I wasn't able to find any existing tests). Once merged, I believe we can close this issue.  I will take a look at doing this tomorrow.

### What about the PaperclipAttachment?
When the `Spree::Config.image_attachment_module` is set to `Spree::Image::PaperclipAttachment` our `Spree::Config.product_image_styles` are passed to `has_attached_file` as seen in the following snippet:

https://github.com/solidusio/solidus/blob/cc56661f4faa0c1cadbf979bef6fddbc53509e54/core/app/models/spree/image/paperclip_attachment.rb#L9-L15

This is a method defined by `kt-paperclip` which accepts these styles and default styles [as defined in the gems documentation](https://www.rubydoc.info/gems/kt-paperclip/Paperclip%2FClassMethods:has_attached_file).  So the configuration is also correctly applied for the `Spree::Image::PaperclipAttachment`.

**Comment by kennyadsl** [comment]
> As this is outdated, I recommend we use this issue to create a PR that updates the documentation accordingly, and adds some tests such that we verify this behaviour (I wasn't able to find any existing tests). Once merged, I believe we can close this issue. I will take a look at doing this tomorrow.

I like the plan, when documenting this, please be aware that not all the Solidus versions support ActiveStorage (I think it has been introduced in 2.11), so we should reflect that in the documentation. Thanks!
