### ISSUE TITLE
Fix the version number

### ISSUE THREAD

**Issue by Shalashtein** [solidusio/solidus#3897]
The version number of the latest release was typed as 2.10.4 rather than 2.11.4

**Comment by jarednorman** [comment]
Solidus v2.10.4 is the latest v2.10.x release and follows v2.10.3. The release was cut after v2.11.3, which is the latest v2.11.x release. I can see how you might have thought a mistake was made as in the version list v2.10.4 is at the top, but that's just because chronologically it was released most recently.

**Comment by jarednorman** [comment]
Correction: v2.11.4 is actually the most recent version of the v2.11.x line. Both v2.10.4 and v2.11.4 exist.
