### ISSUE TITLE
Experiment: disable solidus code reloading

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#399]
We were discussing disabling code reloading of the solidus engines as it really slows down development mode. @gmacdougall suggested we should have the ability to try this out by setting an ENV variable

**Comment by alepore** [comment]
Also, Rails 5 should improve development performance http://weblog.rubyonrails.org/2015/11/11/snappier-development-mode-in-rails-5/

**Comment by dhonig** [comment]
This should be interesting.  Would love to see some numbers on it...

**Comment by tvdeyen** [comment]
@jhawthorn Do you plan to disable it only in sandbox mode or for all apps using Solidus as engine? I defiantly vote against the latter. Especially unexperienced devs always get crazy, if things don't change if they hit refresh in the browser. We started to cache the yml based config files in AlchemyCMS for performance reasons and the people where like WAT? I can't even count the numbers of issues I had to close and questions I had to answer. So consider this, before disabling this globally. 

Also, I think the developer is in charge of configuring their app, not the engine/plugin/gem.

@alepore Yeah, I read this one. Not hoping for another `spring`, though :-1: The Rails core team should start to increase overall performance and remove the cause, instead of monkey patching the symptoms.

**Comment by tvdeyen** [comment]
And where is the performance gain, if I have to restart the rails server, every time I change a class or method? Booting up a rather medium rails app can take several seconds, so I don't see any speed bump in here.

For frontend devs "only" doing CSS/JS, this is ok, but this is easily done in de-activating class reload locally in their app. Best done in a ENV var or something.

Definitely nothing you want to enable globally.

**Comment by jhawthorn** [comment]
The experiment would be to disable reloading of the solidus classes. Which would allow stores depending on solidus to have a faster development environment. The store's models would still be reloaded

This is just desired as an experiment.

**Comment by jhawthorn** [comment]
Closing because this is stale. Still interested in it though.
