### ISSUE TITLE
Nothing happens when trying to install 2.11

### ISSUE THREAD

**Issue by hrqmonteiro** [solidusio/solidus#4018]
I install the gems, then when i try `rails g solidus:install` it just keeps stuck in the command:

![2021-04-06_13-29](https://user-images.githubusercontent.com/17055027/113746120-58b28c80-96dc-11eb-9655-cf838b6915c6.png)

It was like this for more than an hour. Then i created a new project and tried again, and it's stuck until now.

**Comment by cnorm35** [comment]
@hrqmonteiro try running the command: `spring stop` then re-trying the install with the `rails g solidus:install` command

**Comment by hrqmonteiro** [comment]
![2021-04-06_13-45](https://user-images.githubusercontent.com/17055027/113748148-88fb2a80-96de-11eb-9b77-e0c45641de99.png)

Worked but now i got this error.

**Comment by cnorm35** [comment]
looks like that's a separate issue.  I would try creating a new rails app to install solidus and make sure all the gems install successfully and make sure you follow all the steps listed in the installation guide:

https://guides.solidus.io/developers/getting-started/first-time-installation.html

**Comment by jarednorman** [comment]
That second issue might be related to trying to use Ruby 3.0.0 which I don't think we officially support yet. You might try switching to Ruby 2.7 for now.

Regardless, we try to keep our GitHub issues clean of troubleshooting, so you're better off posting in [the Troubleshooting category](https://github.com/solidusio/solidus/discussions/categories/troubleshooting) over in the GitHub discussions. If it turns out there's an actionable bug, then of course create a bug with steps to reproduce and whatever information comes out of troubleshooting.
