### ISSUE TITLE
Solidus 2.11 - commit tagged for release with v3.0 came with upgrading to v2.11.xx instead

### ISSUE THREAD

**Issue by senemsoy** [solidusio/solidus#4133]
[This](https://github.com/solidusio/solidus/commit/8cc77f4d64c793a77a872a5bc9c8ca3aae758401#diff-969f176eee46c6e75cb7074700485de8b5e6c3ad3fa044060a3e465e48203bf0) commit is tagged for release with Solidus 3.0, but somehow we got it when we upgraded from 2.10.xx to 2.11.xx. The commit is tagged with the right version, and the documentation is right, but somehow it is in `solidus_core` with 2.11 and caused issues for us. Orders couldn't be cancelled due to this. Wondering how this could have happened.

**Solidus Version**:
2.11.0

**To Reproduce**
1. Upgrade to Solidus 2.11 from 2.10
2. Run the migrations installer with `bin/rails railties:install:migrations` and `bin/rails db:migrate`.
3. Run the update task with `bin/rails solidus:upgrade:two_point_eleven`.

**Comment by jarednorman** [comment]
The reason for the confusion around the commits is just that the change was backported to 2.11 in [this commit](https://github.com/solidusio/solidus/commit/4e1002c79). My assumption is that while the deprecation would have said the functionality was being in removed in v3.0, that's just because all the deprecation said that.

That said, I don't specifically recall a decision to backport that. @kennyadsl do you recall why that was backported to v2.11?

**Comment by kennyadsl** [comment]
Damn, I think you are right. This was probably my mistake: when backporting things I should have accidentally included this commit while it was supposed to only stay in 3.0.

First of all, thanks for reporting @senemsoy. Now it's a bit of a mess: we can revert the commit and release another patch level, but we could theoretically break stores that already updated to the latest 2.11.x. In practice, I don't think it will happen because if the current code is working, reintroducing the deprecated path shouldn't create any issue. 

@senemsoy Would you mind sending a PR against the 2.11 branch for reverting this commit?

**Comment by kennyadsl** [comment]
We can close this one, the fix has been released with version `2.11.11`. Thanks for letting us know!
