### ISSUE TITLE
Auditing and Comments / Notes

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#429]
There is desire (and a few separate implementations) of auditing and commenting in Solidus stores. Bonobos uses PaperTrail for auditing, and allows comments to be added on top of the audits, to have action-specific notes. There are some concerns about PaperTrail, so let's talk through options here so that we can get something into core.

**Comment by jordan-brough** [comment]
Some quick thoughts:

PaperTrail:

- Seems a bit shotgun-ish.  (Recording every version of every row) Ideally, sure, I'd like to have all the information in the world, but I worry that there is a storage and performance cost here that perhaps we don't need to pay to get what we want.
- Isn't as reliable as I'd like.  Anything that skips activerecord callbacks won't hit the db (`update_all`, or the dreaded `update_columns`, etc).  I've wondered if DB triggers would be a more performant and reliable way to do this kind of thing (store every version of every row) if a store did want to just store every version of everything. (And something like that should maybe live outside of Solidus since it'll be db-dependent and can have other implications.)
- Does not provide as much context as I'd like.  Many tables can be updated from a single change and it's hard to tie those things together in our admin tool.  In a rails console or db console it's even harder.

One thing I'd like to see is for us to get more classes like @jhawthorn's `PaymentCreate` and `OrderUpdateAttributes` classes in https://github.com/solidusio/solidus/pull/357 and outfit them with logging and auditing, so that we could easily provide context like the person making the change and the intent of the changes, alongside the actual changes made.  I'm imagining us coming up with a tool that calculates a summarize diff of the order before and after the class runs, and storing that somewhere.  And make it easy customize or to turn on/off according to the needs and performance requirements of each store.

**Comment by paultyng** [comment]
PaperTrail does have some [configurability](https://github.com/airblade/paper_trail#choosing-when-to-save-new-versions) in terms of when to save a new version, so we could make it a bit more selective, of course that is more work and people will probably disagree on what exactly is important.

**Comment by mtomov** [comment]
I recently came across [Aspect Oriented Programming](https://en.wikipedia.org/wiki/Aspect-oriented_programming).

The idea is not to get those clean and concise single responsibility classes `PaymentCreate` and `OrderUpdateAttributes` and seize the opportunity  to "clearly" add a few more lines before and after each method, but to wrap vertical programming requirements like auditing / logging into an own entity.

One ruby library that does implement the aspect oriented programming is [Aspector](https://github.com/gcao/aspector)

**Comment by gmacdougall** [comment]
Closing due to being stale

**Comment by cbrunsdon** [comment]
For anyone that finds this in the future, this gem now exists and have had good success with it: https://github.com/solidusio-contrib/solidus_papertrail
