### ISSUE TITLE
[API] empty cart endpoint raises 500 error with shipped order

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#4438]
**Solidus Version**:
all, including master

**How to reproduce**
Trying to `empty` a shipped order via API raises a 500 error, which is something we should try to avoid.

This can be easily demonstrated in the admin area:
* on the `Cart` tab, add an item to a new order, and keep this browser window as it is, we'll get back to it later;
* add the address, payment, and finalize the order in a different browser window/tab;
* ship the order;
* go back to the `Cart` browser window and click the `Empty Cart` button. Web developer tools will show a 500 error, and no message is presented to the user.

**Context**

This is the method definition from the [API orders controller](https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/orders_controller.rb):
```ruby
      def empty
        authorize! :update, @order, order_token
        @order.empty!
        render plain: nil, status: 204
      end
```

`@order.empty!` [tries to reset the cart](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L450) by destroying the associated records, but shipped shipments [cannot be destroyed](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/shipment.rb#L340). The error bubbles up to the controller, where it's not handled. 
<img width="787" alt="Screen Shot 2022-06-22 at 11 18 08 AM" src="https://user-images.githubusercontent.com/141220/174998935-d6aef9a6-58ef-4412-8d1e-91d4953879cb.png">

**Comment by dborovsky** [comment]
Hi @kennyadsl  I'll investigate and fix it.

**Comment by nirnaeth** [comment]
I tried to reproduce the issue in various ways

**Customer with 2 tabs **
1. the customer issues the order on tab A, ends on user/cart
2. the customer goes to user/cart on tab B and finalizes the order 
3. the admin approves the order, captures the payment, ships the order
4. the customer goes to tab A and empties the cart

outcome: cart is emptied with no error in the console

**Customer / Admin**
1. the customer issues an order
2. the admin approves the order, captures the payment
3. the admin empties the cart on admin/cart 

outcome: cart is emptied with no error in the console

**Customer / Admin**
1. the customer issues an order
2. the admin approves the order, captures the payment, ships the order

outcome: admin/cart disappears (expected)

I don't know if this was fixed somehow else and I'm not extremely familiar with solidus to understand if I'm doing something that doesn't exactly match the description of the issue, but from what I can see it looks to me like the issue is not reproducible anymore.

**Comment by nirnaeth** [comment]
I have issued a PR to fix the problem. Code works, but I need advise on the test and on how to redirect properly to the order
