### ISSUE TITLE
Implement available_until on products / variants

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#465]
To be able to easily set an end availability date

**Comment by jasonfb** [comment]
do you want me to just pull request Spree PR #6794 against Solidus?

without un-deleting already deleted records, you still retain a host of bugs related to nil objects. The bulk of the heavy lifting in Spree PR 6794 is to backport the change to eliminate the ```undefined method for nil bugs```, which was the primary driver for me (the feature of discontinuing in the future was an added bonus).

**Comment by jhawthorn** [comment]
@jasonfb thanks, but I have a few reservations about spree/spree#6794. I don't think the migration is appropriate (turning deleted products into discontinued products), as that may have significant behaviour differences in stores' custom code. `acts_as_paranoid` was not removed from the product, despite some of its necessary functionality being removed. There were also unrelated changes I would prefer to be reviewed separately (fixing line items of deleted products, for example).

What we'd like to see, at least initially, is a minimal PR implementing the `available_until` without breaking existing functionality.

**Comment by jasonfb** [comment]
Yes I understand the reasoning behind moving slowly. However, adding a discontinued_on (or available_until) was not the primary objective of my work, the primary objective was to fix the dozens and dozens of bugs I have seen across multiple stores that are related to deleted objects. That issue has cost literally hundreds and hundreds of hours of developer time. That was the primary objective, the added feature was a side-benefit.

You're right it is a significant change, and upgraders would need to re-think their scoping mechanisms if they aren't already using the patched ```available``` scope. 

>> acts_as_paranoid was not removed from the product, despite some of its necessary functionality being removed

I'm not sure what you mean by this. By "its necessary functionality" are you referring to the ruby magic that happens to mysteriously re-show deleted objects? That's an anti-pattern, and leads to very bad bugs, and no one should code like that. It's true I left ```acts_as_paranoid``` in there, for when you really do want to delete something, but you shouldn't make deleting a normal part of a workflow. 

As far as "fixing line items of deleted products" I think you are referring to the rake task, which only happens if you run it explicitly, of course, and you will note the migration does not edit any line items. 

I do realize it's "seems" like a drastic change, but in my view simply adding a small ```available_until``` feature is just a small band-aid when the real problem is the flawed design and the dozens and dozens of bugs created by the design. Without address the root problem it seems like you aren't actually fixing what is arguably one of the worst bugs in Spree itself.

**Comment by athal7** [comment]
@jasonfb It's less about moving slowly, and more about having the updates to Solidus be easy for stores to upgrade, and having the commits be single-purpose so that they can be easily identified or rolled back as necessary. If there is important cleanup work on products as well, let's evaluate that separately (even if before) from the available_until feature.

**Comment by jasonfb** [comment]
Yes ok I understand, thank you for your patience. In that case my issues about the nil bugs can be considered off-topic to this specific GH issue as you had originally filed it.

**Comment by athal7** [comment]
@jasonfb sounds good, I like fixing nil bugs too though :)

**Comment by jasonfb** [comment]
this never got in Solidus did it? @jhawthorn @athal7 -- upon (6 months of..) consideration, I think we should indeed go with @jhawthorn's original suggestion which was just to add the available_until (although I'd recommend discontinued_on so that all the timestamp fields consistently end with _on ) at this time, laying the groundwork for the switch-over.

To that end, we can make *both* the db migrate and the rake task you see in https://github.com/spree/spree/pull/6794 into rake tasks, with instructions for how to use them. That way, this change is not forced on anyone and they can use the rake tasks to clean up their own data.

**Comment by bbuchalter** [comment]
I'd also advocate a shared "time gating" module to implement this behavior. It would be nice if all time gates behaves the same in the system so things are consistent for admins. Perhaps we should start by extracting the existing time gate behavior for promotions?

**Comment by mamhoff** [comment]
While time gating looks like very similar behaviour in different models, some things have needs that are really quite different from others. For example, `Spree::Promotion`s `starts_at` field would be poorly named if used in the context of a `Spree::Product`. When I took a stab at making historic pricing happen, I went without an `expires_at` (or equivalent). I don't like the idea of a shared module or mix-in for this functionality. 

Still, I'd like to see some conventions in place so that we don't end up with

* `valid_from`
* `expires_at`
* `active_on`
* `starts_at`

... and so on, all meaning very similar things. What about a naming convention like 
`#{adjective}[_from,_until]`:

`Product#available_from / Product#available_until`
`Promotion#promoting_from / Promotion#promoting_until`
`TaxRate#valid_from / TaxRate#valid_until`
`ShippingMethod#operational_from` / ShippingMethod#operational_until`

(I'm not to keen on the concrete adjectives, just on the pattern)

**Comment by bbuchalter** [comment]
I believe you could implement the module responsible for parsing time gate logic such that the attributes which provide the data were abstracted away with an interface. Does that make sense?

**Comment by mamhoff** [comment]
I think that can be done, with an API kinda like this: 

```
class Spree::MyModel
  time_gated_by :available
```

**Comment by bbuchalter** [comment]
I think it's worth trying.

**Comment by jasonfb** [comment]
@bbuchalter -- I'm not exactly sure how an abstraction of the field's name would serve a greater purpose; at some point, we're gonna have to add a field (or two) and name it something. But all that a field-name abstraction would achieve is letting different stores have different data models, which becomes less-than-desireable, for example, when a 3rd party tries to build an integration against the 'solidus 1.3' data model, for example. (Unless i'm missing the point of the proposed field-name abstraction)

Although I like the idea conceptually, it seems like it would have greater power when applied to something like a scope override (which, incidentally, this feature upgrade will need too)

for example, our in-app (messy) ```available``` scope looks like this
```
  scope :available, -> (available_on = nil, currency = nil) {
    scope = joins(:master => :prices).where("#{Spree::Product.quoted_table_name}.available_on <= ?", available_on || Time.now)
    unless Spree::Config.show_products_without_price
      scope = scope.where('spree_prices.currency' => currency || Spree::Config[:currency]).where('spree_prices.amount IS NOT NULL')
    end
    scope.not_discontinued
  }
```

I could see an abstraction for something like so:

```
make_available_using :available
```
(:available being the existing scope), so that a store could re-implement their own availability scope without having to overload the existing ```:available``` scope

 ```
make_available_using :available_for_realz
```

**Comment by jasonfb** [comment]
FWIW, we just have ```discontinued_at``` on both spree_products and spree_variants. The only thing that mildly bothers me about the naming convention is that in the Spree/Solidus world, some timestamp fields end with ```_on``` where was outside of Spree/Solidus the convention I have seen in nearly all other Rails apps I have works on is to end timestamp fields with ```_at```. 

but I could go either way on that point. to keep parallel with ```available_on``` I'd just suggest ```discontinued_on````

**Comment by cbrunsdon** [comment]
If anyone wanted to send a PR to implement this I think people would be happy to see it, but closing the issue due to staleness.
