### ISSUE TITLE
Heroku + S3 = img's with expiry

### ISSUE THREAD

**Issue by ddvorkin14** [solidusio/solidus#4658]
There is no clear documentation around how to properly setup the s3 bucket and the solidus instance on heroku so img's dont expire.... Whats strange is the img's dont expire on the solidus backend panel, its only on the customer facing front end views

**Solidus Version**:
3.1.7

**To Reproduce**
deploy to heroku with s3 config, upload an img, visit the customer facing ui, wait 5 min and the img will expire and will not display

**Current behavior**
the img link is expiring on the frontend and its a bit confusing why

**Expected behavior**
Im expecting for the url to the img to refresh or reload or something

**Screenshots**

![Screen Shot 2022-10-04 at 10 15 01 AM](https://user-images.githubusercontent.com/102325794/193843050-87c8c642-6054-44d2-bda3-def0258cf1c3.png)

**Desktop (please complete the following information):**
 - OS: HEROKU
 - Browser Chrome

**Comment by jarednorman** [comment]
Yeah, this is one of the most common issues people run into that gets reported in the Solidus Slack #support channel. The backend isn't an issue because there's no caching.

The frontend runs into the issue that much of the product show and listing pages are cached, so when the expiring URLs are generated, they get reused beyond the lifespan of the generated image URLs.

**Comment by ddvorkin14** [comment]
So what is the recommendation here because im running out of ideas haha

**Comment by jarednorman** [comment]
If you set the bucket policy to make all objects in the bucket public, that'll solve it.
