### ISSUE TITLE
tailwind and sassc-rails issue

### ISSUE THREAD

**Issue by sulemanuzair** [solidusio/solidus#4685]
Can't use tailwind with solidus due to sassc-rails gem on production

**Solidus Version**:
3.2 Latest

**To Reproduce**
Integrate tailwind css in a rails 7 application with solidus.

**Current behavior**
SassC::SyntaxError: Error: Function rgb is missing argument

**Expected behavior**
It should compile the assets

**Screenshots**
<img width="668" alt="Screenshot 2022-10-23 at 10 06 26 AM" src="https://user-images.githubusercontent.com/52164568/197374874-ab6a36d5-a81a-4e63-8779-9efff199ed33.png">

**Comment by sulemanuzair** [comment]
Also, in [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) gem repo, it says to remove sassc-rails from gemfile

**Comment by peterberkenbosch** [comment]
@sulemanuzair in your `config/application.rb` add this: 

```ruby
config.assets.css_compressor = nil
```

**Comment by gsmendoza** [comment]
Hi @sulemanuzair ! I wasn't able to reproduce the error you're having. Please see https://github.com/gsmendoza/solidus_store/tree/rails-7-0-4--solidus-3-2-2--4685-tailwind. I was able to run `bin/rails assets:precompile` there with no issues.

Can you compare your app with https://github.com/gsmendoza/solidus_store/tree/rails-7-0-4--solidus-3-2-2--4685-tailwind? You may also want to update the rails-7-0-4--solidus-3-2-2--4685-tailwind app so that it reproduces the issue you're having.

**Comment by sulemanuzair** [comment]
Thanks @peterberkenbosch and @gsmendoza. 

I added `config.assets.css_compressor = nil` in application.rb and production.rb earlier too (as it was occuring only for production). Adding it resolved this issue, but that created some other issue in the app, which was unrelated to this particular issue. Closing the issue now.

Thanks again
