### ISSUE TITLE
[Admin][UI][Bulk actions] Require confirmation before completing bulk deletes

### ISSUE THREAD

**Issue by forkata** [solidusio/solidus#5740]
Currently, bulk deleting resources such as products happens without confirmation. This is not ideal, so we want to introduce a manual confirmation step. 

There's no specific design for this, but we can reference what we have for [deleting a product](https://www.figma.com/file/h7eZRxh8KhPakTMr7c9NlB/Solidus-%E2%80%94-Admin-Dashboard?type=design&node-id=440-38713&mode=design&t=DEHtW0g4eMtrAENH-0) with a different copy such as 
```
Remove 3 products?
This can't be undone.
```

![Image](https://github.com/solidusio/solidus/assets/141220/7163fe7f-ecc5-4165-84f9-0e52fce3cf0b)

**Comment by forkata** [comment]
The first part of this is done, which is adding the ability to confirm a batch action. I think we may want this to be the default behaviour for all batch actions?

The second part is implementing the modal instead of the default browser confirm dialog.

**Comment by forkata** [comment]
First part of this change was merged here https://github.com/solidusio/solidus/pull/5702

**Comment by MadelineCollier** [comment]
The second part of this work (converting the `window.confirm()` alert to a custom styled modal) was started in [this PR](https://github.com/solidusio/solidus/pull/5818) but was cancelled and closed after it became clear that it would be a decent amount of work to redesign this flow (unlike the `window.confirm()` method, modals don't block JS execution while they wait for user input, and disrupting the form submission with `e.preventDefault` to await a promise also had its complicating factors).

Since we have other larger admin features that still require work, for now we are closing this issue. In the future, if we have extra time on our hands to spend on purely visual changes rather than functional ones, we can revisit this issue, but for now we will focus on the large outstanding backlog of admin features!
