### ISSUE TITLE
Is it possible de develop extensions for Solidus ?

### ISSUE THREAD

**Issue by LyesBe** [solidusio/solidus#577]
I found many tutorials about extension developing on Spree but none on Solidus. I assumed that the process was the same but I am facing many compatibility issues on gems problems that I did not face with Spree.

**Comment by tvdeyen** [comment]
Yes, this is definitely doable. Lots of community members already started to port common extensions under the [solidusio-contrib GitHub organization](https://github.com/solidusio-contrib).

While porting other extensions two things need to be ensured:

1. The spree gem dependencies in the extension `.gemspec` file needs to be update to require the solidus gems instead. So, a dependency to `spree_core` needs to be `solidus_core`, `spree_backend` to `solidus_backend` and so on.

2. The code base needs to be compatible with Spree 2.4, because Solidus was forked form Spree 2.4.

**Comment by LyesBe** [comment]
In fact, I had Spree 3.0 installed and it was the cause of the compatibility issues. Also, I didn't change the names of the dependencies. Putting "solidus_foo" instead of "spree_foo" solved the rest of the issues.
Thank you for your answer, it was helpful. :)

**Comment by tvdeyen** [comment]
Glad to here that! @cbrunsdon close, plz.
