### ISSUE TITLE
General Query

### ISSUE THREAD

**Issue by aneeshjajodia** [solidusio/solidus#587]
Hello,

Am really sorry for posting such a general query in here. But I wasn't able to find a place to post the general query and is why I thought this would be an option. (Couldn't find twitter handle and email address too).

So, basically I've been running my eCommerce website using WooCoomerce over Wordpress. Obviously as we all know, Wordpress is not built for eCommerce, and is not so preferable either. (www.creativecases.in)

I was following spree for sometime now, basically I have a plan on a new e-commerce website for my own company with certain unusual capabilities like artists uploading their own artworks, commission calculations and etc. I was planning since sometime on what to go ahead with. That's when I found this to be a fork of Spree.

I wanted to know, is this a preferable platform for such kind of thing? 

And layout, if something of this sorts is possible www.chumbak.com.

Would be glad if someone can help me through planning this.

**Comment by gmacdougall** [comment]
Thanks for your interest in Solidus! This is a platform in which you'll be able to developer the type of functionality you desire, however it will take a good deal of custom development.

I might recommend you check out the Slack channel (http://slack.solidus.io/) for some people to discuss this with. In order to keep our issues list manageable, we like to keep the issues for active development on the project rather than discussions about how to use the project. As such, I'm going to close this issue.
