### ISSUE TITLE
Add MSRP and Sales Price to Product

### ISSUE THREAD

**Issue by fthobe** [solidusio/solidus#5902]
**Desired Behavior**
Add an MSRP and Sales field to the product resource allowing to display on front-ends messages such as: 
10.00€ instead of 14.99€

**Current Behavior** 
The current extension linked below does not work and given that we are talking about two fields they might be better suited for core than for an extension. 
[Sales Price](https://github.com/solidusio-contrib/solidus_sale_prices)

**Comment by jarednorman** [comment]
Sale pricing works too differently from store to store for this to be sensible thing to add to core.

MSRP is an interesting idea, but you have to consider that Solidus supports multiple currencies, which would mean that each variant could have many MSRP prices across different currencies and countries. I would recommend that stores wishing to implement this add an MSRP flag to `Spree::Price` and use a customized price selector that excludes those prices from normal selection. You could then leverage the existing price UI for managing MSRP prices for each currency/region and write a small amount of custom code to look up MSRP given some pricing options.

I'm open to hearing what the rest of @solidusio/core-team thinks, but I tend to think this doesn't belong in core. Could be a good extension, though.

**Comment by tvdeyen** [comment]
> The current extension linked below does not work

We are happily accepting PRs to revive the extension

**Comment by fthobe** [comment]
Hey folks, 

@tvdeyen yes, you fully understood the feature request. 

@jarednorman I followed your request and I am trying to understand the core baseline feature set about seo here: #5905 

It would be great if you two help me and make me understand inside the discussion what's the standard to maintain and we will see if we can reconcile that with what we have in mind to contribute it to core.

**Comment by jarednorman** [comment]
> It would be great if you two help me and make me understand inside the discussion what's the standard to maintain and we will see if we can reconcile that with what we have in mind to contribute it to core.

What does and doesn't belong in core is always a judgement call. We have to weigh how this will impact existing stores and how it will benefit new stores, as well as the maintenance burden. In case of this feature, pricing is already something that's designed to be customized and lots of stores take advantage of that. Because of that, it would be difficult to implement this in a way that isn't likely to interfere with (or otherwise conflict with) the customization in existing stores.

I hope that helps. Closing this issue for now. MSRP would be a good extensions and the sale pricing extension needs some updates to work with the latest versions of Solidus, but that should not be too difficult for whoever undertakes it.
