### ISSUE TITLE
Spree::Promotion#usage_count query is slow

### ISSUE THREAD

**Issue by magnusvk** [solidusio/solidus#600]
This is how we currently query the current usage count of a promotion:

```
    def usage_count
      Spree::Adjustment.eligible.
        promotion.
        where(source_id: actions.map(&:id)).
        joins(:order).
        merge(Spree::Order.complete).
        distinct.
        count(:order_id)
    end
```

This query is slow to the point of having caused an outage for us.

I tried playing around with this query to make it faster:

```
count = 50
result = Benchmark.bm do |benchmark|
  benchmark.report('old query') do
    count.times { Spree::Adjustment.eligible.promotion.where(source_id: actions.map(&:id)).joins(:order).merge(Spree::Order.complete).distinct.count(:order_id) }
  end
  benchmark.report('tweaked query') do
    count.times { Spree::Adjustment.eligible.promotion.where(source_id: actions.map(&:id)).joins(:order).merge(Spree::Order.complete).count('DISTINCT spree_adjustments.order_id') }
  end
  benchmark.report('new query') do
    count.times { Spree::Order.complete.joins('JOIN spree_adjustments on spree_adjustments.order_id = spree_orders.id').where(spree_adjustments: { source_id: actions.map(&:id) }).merge(Spree::Adjustment.promotion).merge(Spree::Adjustment.eligible).count('DISTINCT spree_orders.id') }
  end
end
```

Unfortunately, this doesn't result in a significant improvement. I won't be able to do this myself, but wanted to document this issue for the future. My current thinking is that we may have to cache the usage limit on promotions.

**Comment by jordan-brough** [comment]
I think it might be worth adding a separate table for counting promotion usage.  It seems reasonable to me to make this an explicit data point instead of being inferred.

Something like:
promotion_usages(id, promotion_id, promotion_code_id, order_id)

I don't think implementing this would be harder than implementing a counter cache, and would carry roughly the same costs (in terms of denormalization).  It would have the added benefits of being more explicit, more relational, easier to write a no-downtime migration for, and potentially providing a good place in the future for SQL-y things (like using SQL transactions and locking to prevent race conditions from allowing a promotion usage to exceed the allowed amount).

Stepping back for a second, here are three ideas so far on solving this problem:

a) Make the query faster
b) Add counter cache columns
c) Make usage counting explicit

How do people feel about those options and are there any other ideas out there?

**Comment by Bahanix** [comment]
:+1: 
Whether there is a Spree::PromotionUsage or not, a usage_count/current_usage counter cache in Spree::Promotion would be very useful to me.

**Comment by mtomov** [comment]
:+1: for a separate table due to the SQL reasons you outlined (double counted of orders & sql locking), while it being roughly the same effort.

**Comment by mtomov** [comment]
Hello,

Want to highlight that those queries are indeed a problem during `Order#populate`, and one such takes `140ms` to run in our case. 

On Solidus 1.2, during a populate - 6 of them run. I will check now how many they are on more recent versions.

**Comment by jhawthorn** [comment]
Closing due to staleness.

This code has changed a bit but may still be slow. It may be cacheable or may be unavoidable. Closing until there is an actionable proposal on how to improve this.
