### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by travisp** [solidusio/solidus#639]
While trying to access ```/admin/orders``` on a fairly new solidus installation, I encountered the above error message, ```translation missing: en.spree.stock```

Interestingly,

https://github.com/solidusio/solidus/blob/master/core/config/locales/en.yml

does not seem to have en.spree.stock, while,

https://github.com/spree/spree/blob/master/core/config/locales/en.yml

does have en.spree.stock (set to "Stock")

**Comment by tvdeyen** [comment]
You're comparing Spree master with Solidus master. They are completely different. The fork was made from Spree 2.4. The current spree master is 3.1.beta. 

But, yeah. This is easily fixed in your local app. Just add a `config/locales/spree.en.yml` file and add the missing translation. You also could send a pull request that fixes that. But since the translations get an overhaul in #549 and general translations like `Spree.t("stock")` will be replaced with Model attribute translations anyway, you could spare this and just fix this in your local app. 

Thanks for reporting.

**Comment by travisp** [comment]
I wasn't aware of the translation overhaul. Without that it would probably be worth doing an audit of the translations to see what might be missing, but it's probably not worth it at this point. Thanks and closing this issue.
