### ISSUE TITLE
README.md: Add note about view customization

### ISSUE THREAD

**Issue by dt1973** [solidusio/solidus#678]
Could we add a note to README.md on how to copy all of Solidus' views into ones own `app/views/` folder for customization? Ie.:

https://github.com/rubysherpas/forem#view-customisation

**Comment by tvdeyen** [comment]
This is more something for a guideline/wiki than the README. A README is more a "how to install" for developers than a user guide. Also this is common rails knowledge. 

Please don't feel offended, but from that's a 👎

**Comment by hakkiplaten** [comment]
Not common knowledge to everone. We can't expect all our users to be experts.

Usually when I install Forem one of the first things I do is to copy all the views to my own app so I can start customizing. Solidus' default layout is pretty amateurish, so any serious developer would most certainly start modifying the views, CSS and JS right away in order to create something that is more beautiful and more likely to bring in sales.

I just think it's an important piece of info that shouldn't be left out of the main docs. Which is why, probably, Radar placed it in his main docs. And as we know, nobody's done more for Solidus than him.

**Comment by gmacdougall** [comment]
It certainly deserves a place in the Wiki at a minimum. Perhaps we should then link to some of the more commonly asked topics in the README.

**Comment by tvdeyen** [comment]
Yes, a link to FAQ/Wiki ist great for the README, but a README is not "main docs", that was my whole point.

**Comment by abhishek77in** [comment]
:+1: I am using `solidus` for my project. It would help to see this information in Readme or at the least in Wiki. Thanks.

**Comment by dpsk** [comment]
:+1:  on this one

**Comment by tvdeyen** [comment]
If someone sends a pull request we would be happy to merge this in. Also, the Wiki is public writeable. Contributions are welcome.

**Comment by jasonfb** [comment]
@dt1973 @hakkiplaten are you recommending that someone copy *all* of the views from the Solidus core code into one's own app? This is not really considered best practice. Generally people copy only views & partials that they want to override from the core code, not all the views in one copy. 

I think there should be a specific guide for "Customizing Solidus" which should cover this topic indeed, as well as other ways to customize, but I wouldn't recommend a full copy of all the view files into your own app.

**Comment by mtylty** [comment]
👍 for leaving the README alone and using guides/wiki

**Comment by hakkiplaten** [comment]
@jasonfb I personally wish to do the HTML from scratch because I believe I can make it even simpler and more semantic, thus achieving greater power and flexibility when it comes to making the site look like a million bucks. At least during Spree's days, the HTML was a mess. Not sure how it is now though. But ofcourse, I can easily understand how this is not everybody's cup of tea.

**Comment by cbrunsdon** [comment]
We've hired a documentation writer to update how to best customize solidus, so this will get covered under his scope.
