### ISSUE TITLE
[Enhancement] Humanizer on user's account creation

### ISSUE THREAD

**Issue by JoaoGFarias** [solidusio/solidus#694]
Currently, the user's account creation just validate if the e-mail is formatted correctly and if the password matches its confirmation input.
I think a gem like [Humanizer](https://github.com/kiskolabs/humanizer) could be added in this area to ensure a real user if trying to create an account.

Below is screenshot from the Humanizer in action; it asks a question which only intelligent humans could anwser.

<img width="1279" alt="c1aca838-9b6f-11e5-9688-86324be791a7" src="https://cloud.githubusercontent.com/assets/1585655/12327560/0a4db6e4-bab6-11e5-966d-50b02b7ff88b.png">

What do you think about it?

**Comment by gmacdougall** [comment]
Authentication right now is handled through `solidus_auth_devise` rather than the main project itself. I don't think we wish to enable this by default for anyone, and would prefer to allow individuals to decide on if they want something like this for their own stores.

Please feel free to develop a fork of `solidus_auth_devise` that integrates this in. This could be used as an alternative to the existing `solidus_auth_devise`.

**Comment by tvdeyen** [comment]
This is very specific to the store itself. I don't see this in `solidus_auth_devise` either. This is something the store can include on its own. 

Maybe an extra extension.
