### ISSUE TITLE
You must create a default country before creating a stock location.

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#722]
Hi,

I get this message when I try to add a new stock location.
I have added a few countries, but I could not see any options for selection any of them as default.

Where can I select a default country? It would be nice if the error message also linked to that page. :-)

--
Martin

**Comment by gmacdougall** [comment]
The default country is managed through configuration:

https://github.com/solidusio/solidus/blob/v1.2.0.rc1/core/app/models/spree/app_configuration.rb#L120-L123

If you're having issues like this, please address them to places like Stack Overflow or the support channel on Slack. We like to keep issues on Github focused on features or problems with the code base rather than how to use Solidus.

Thanks for your interest!
