### ISSUE TITLE
Use ActiveRecord translations for admin forms

### ISSUE THREAD

**Issue by cbrunsdon** [solidusio/solidus#735]
This is a meta-issue to track progress against the PR's required to move the admin translations to us the activerecord attributes.

The admin is far too unfriendly to i18n and we need to ensure it works properly for non english speakers, and the best step forward is to use the rails-provided translation mechanisms properly.

This is meant to carry through the exploratory work started in #549.

**Comment by tvdeyen** [comment]
:+1: Let me know, if you need any help

**Comment by Murph33** [comment]
Will do, thanks!

**Comment by Murph33** [comment]
So I feel totally happy with the first commit I just have one thing I want to touch base on before I set up a PR.

https://github.com/magiclabs/solidus/commit/056dfdfb74ef137fc5d05454016df9176f3e8eaf#diff-3

Here you've changed away from including the span using a content tag as part of the label to just writing it out explicitly.  The only functional difference is obviously clicking the * now won't select the field.  Just wanted to address this other change before putting in a PR since it isn't really part of switching to better I18n use.  I don't' know if across the entire project this will increase or decrease consistency or if one of these is generally a better practice we want to use.

**Comment by tvdeyen** [comment]
@Murph33 Yeah, I changed that primarily for performance reasons.There is no need to create a static HTML tags with costly rails view helpers. 

But, this is out of scope of this PR, so I guess we should skip this in order to not pollute the diff with non related stuff. What are @cbrunsdon and @jhawthorn thinking?

**Comment by cbrunsdon** [comment]
Honestly I'm fine with it in this PR. 
Its the same output and more readable. Just do it in a separate commit and we're good IMO.

**Comment by Murph33** [comment]
:+1: Will do.

**Comment by jhawthorn** [comment]
@tvdeyen I have a different plan to remove the `*`. Those are a pain point for me because it messes up capybara's matching: you might have to `fill_in "Name *", with: "My Name"`. It also pollutes our markup with something which IMO is a style concern. I plan to open a PR where we change it to

``` html
<label class="required">Name</label>
```

``` css
label.required:after {
  content: " *";
}
```

**Comment by tvdeyen** [comment]
@jhawthorn That's why the `<span>` is not part of the label in my change. I'm also fine with your solution. Easier to override for people that don't want the `*` in the forms.

**Comment by Murph33** [comment]
Appears to be some orphan Spree.t(:back_to_countries_list) translation that doesn't even have an entry in the en.yml  
It only shows up on the admin page when you're adding or editing a country
https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/countries/new.html.erb
https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/countries/edit.html.erb
https://github.com/solidusio/solidus/blob/master/core/config/locales/en.yml
Just add it in as a general translation in a different PR?  I don't think it can be cleaned up the way the other things are.

**Comment by cbrunsdon** [comment]
> Is cleaning out en.yml of unused translations even a concern?

Not right now at least :D.  Lets focus on getting the forms moved into the right places and deal with the rest later.

**Comment by tvdeyen** [comment]
We should at first only address the form translations and fix the other stuff later. Removing unsused translations should be another PR. 

Maybe we could deprecate them. Therefore we could pimp the `Spree.t` and log a `ActiveSupport::Deprecation` if a deprecated translation was used. But this is a lot of extra stuff to be done. 

Should we maintain a list of moved translations at least. So we could show the list in the release notes?

**Comment by Murph33** [comment]
For sure that makes total sense

Right now I'm looking at https://github.com/magiclabs/solidus/commit/efc9c6cae613649ec2eceaa21ce0f903eb5c1074#diff-4 and it's not a big difference but that has changed the for attribute of the label so now it's pointing towards `customer_return_stock_location_id` instead of `customer_return_stock_location` which wouldn't matter except there is a select2 element at the top of the screen with the same ID so now clicking the label takes you to the top of the screen instead of doing nothing like before this change.  Could change it to something like `<%= f.label :stock_location_id, for: "nil" %>`.  I don't know how the select2 box is really generated and how simple it would be to change it's ID or if that's really a thing.  

The one other change I made was replacing `<%= Spree.t(:item_received?) %>` which didn't have a translation even with `<%= Spree::ReturnItem.human_attribute_name(:item_received?) %>` and adding the corresponding entry in the dictionary but I'm now wondering if that doesn't really fit.

Just want to get these couple things sorted out before I submit another PR.

**Comment by tvdeyen** [comment]
We need to avoid the duplicated id. Good catch!

I think we should change all labels referring to foreign keys to use the human class name of the referred object. 

Taking the example from above:

```erb
<%= f.label :stock_location, Spree::StockLocation.model_name.human %>
```

This will most likely be the best option and we won't need to have duplicate translations for the same thing.

**Comment by Murph33** [comment]
It's not a duplicate ID that is the problem it's that the label is now pointing towards a different ID than it had been before
```html
<label for="customer_return_stock_location_id">Stock Location</label>
```
instead of
```html
<label for="customer_return_stock_location">Stock Location</label>
```

Adding the other explicit part of the name doesn't fix this issue as it's kind of a convergent thing with the select2 hidden box created at the top of the screen.  We need to either explicitly change the ID of the select2 box (I don't know if this is simple or easy) or explicitly set the `for` attr for this label.  I don't know if moving forward other labels will have a similar problem or not.

**Comment by Murph33** [comment]
https://github.com/magiclabs/solidus/commit/2769c23edb4960430a64cdc128f3a8efb2b62dc4#diff-7

I feel like someone either didn't know or didn't care how they used I18n.  `are_you_sure_you_want_to_delete_this_record` has never existed in en.yml.

Was the idea something like someone else localizing it sees that and just makes an entry for that in their own localization?  Either way the orphaned things that never had translations are a little concerning.

**Comment by Murph33** [comment]
@tvdeyen Hey I had a quick question on the `actions.ship` portion: https://github.com/magiclabs/solidus/commit/2769c23edb4960430a64cdc128f3a8efb2b62dc4#diff-11 was wondering if it being the only uncapitalized one was intentional and not replacing the other two occurrences of Spree.t(:ship) in the code (both in https://github.com/solidusio/solidus/blob/4aed3fe7d9dd8d98c1360e54253589f8da91cd9b/backend/app/views/spree/admin/stock_transfers/tracking_info.html.erb )

Thanks again

**Comment by Murph33** [comment]
@tvdeyen has pointed out the need to pretty much have all characters be inside I18n translations and to use more interpolation in #796 and I think that's a very valid point I hadn't really considered.  I will take that into account and revise the problematic changes.

**Comment by tvdeyen** [comment]
Thanks @Murph33 

One important thing is grammatical syntax rules. English and German are similar in grammatical syntax, but the majority of languages have completely different rules. So composing sentences in the UI from two or more translation keys are not useful for most languages. 

One example is the "no resource found" action on all admin collection views, mentioned in #796

These composed sentences needs to be replaced with more complex translation keys including interpolation variables. The downside is, that we need to introduce nested translations in order to get links inside these translations. But this is better then the current state.

**Comment by Murph33** [comment]
The no resource found action commonly has a conditional in a middle of it.  Happy medium to split it into two separately translated sentences?  1) "No #{thing} found."   2) "Add a #{thing}."

I don't think conditionals in the middle of I18n translations are really things.

**Comment by tvdeyen** [comment]
Yes. A notice about the missing things and then outside the notice a button with the action to create one.

**Comment by Murph33** [comment]
Just thought I'd mention here that while I'm not touching the `Spree.t(:no_resouce_found)` problem right now in the new PRs I'm planning on handling that in one commit (or PR) to handle all instances of it at once instead of having it spread throughout ~20  other PRs.

**Comment by Murph33** [comment]
We talk about some things "state" and it's "status" fairly interchangeably since they are synonyms.  Do we want to change that to only talk about the "state" of something at least in regards to things that have their model attribute as state?  

``` 
shared/_order_summary.html.erb

<dt id="order_status" data-hook><%= Spree.t(:status) %>:</dt>
 <dd><span class="state <%= @order.state %>"><%= Spree.t(@order.state, :scope => :order_state) %></span></dd>
```

In particular I'm talking about times like this where we're explicitly showing the order's state but we call it its status.

**Comment by Murph33** [comment]
In reference to https://github.com/solidusio/solidus/pull/856#discussion_r52799804:   

Right.  I forgot that that was the preferred implementation.  It might make the most sense to do one PR after all the other ones are merged to make these changes in one fell swoop since I believe some have already been merged in where the name of a foreign key was put in as an attribute on a different model in the dictionary.

**Comment by cbrunsdon** [comment]
Closing this! All the commits are merged, congrats @Murph33 and thans @tvdeyen
