### ISSUE TITLE
Adapt Spree Guides for Solidus

### ISSUE THREAD

**Issue by henwen** [solidusio/solidus#852]
Spree's developer, user, and API [guides](https://guides.spreecommerce.com/) are excellent primers on the platform, but it's hard to know what content is still relevant for Solidus.

It'd be great to have updated versions of these on [solidus.io](solidus.io). The User Guide seems like a good place to start given the lack of non-developer resources on solidus.io.

_______

_Related musings_ –  Choosing an eCommerce platform is often a joint decision between devs and non-devs (and often, the latter have final say). It'd be awesome to have more content/marketing that makes it easier for us devs to sell our non-dev colleagues on Solidus. This was a problem with Spree to an extent too – it remains fairly obscure compared to Shopify and Magento, who market heavily to non-devs and have very high brand awareness. Obviously, those are different animals as more out-of-the-box solutions, but there's no reason an open-source platform can't be a household name in this day and age. To the moon! :rocket:

**Comment by ajkamel** [comment]
I agree, I think having a good base set of guides to get started with Solidus would be key.  Starting with the Spree guides would be a great starting point.  No to find time to do this. :)

**Comment by yeonhoyoon** [comment]
This is a very important concern for our team, and I assume it is the same for others as well.

**Comment by cbrunsdon** [comment]
To be completely transparent, we know its a huge knock against Solidus as a project that we don't have anything near reasonable documentation.

Good documentation is going to be incredibly important for the long-term success of the project, but we're balancing fixing all the crazy inherited technical debt of the project vs documentation for new users.

While this won't always be true, its been more important for Stembolt and the rest of the solidus team to focus on fixing core and the ecosystem around it, rather than taking time away from core improvements to focus on docs. I'd expect that over the next 6 to 9 months that to change and the developer docs start to get into a space they're actually useful. 12 months from now I'd expect even user docs start to shape up and be more usable.

Of course, thats all assuming we're going at the current speed we're going at. If more people from the community wanted to pitch in and push the docs forward I'm sure we can get them done much faster. 

I know its been a big priority for @jasonfb from conversations in the past, we might be able to get a bunch of people that want to get it done ASAP and push it forward.

**Comment by jasonfb** [comment]
:+1: 

am I crazy to suggest something like MediaWiki as a 'scratch pad' for writing docs? (Maybe not even the 'final home' of said docs). I guess what I'm envisioning is something so easy to edit and community-oriented and MediaWiki seems like it takes away all the Git workflow and pull request stuff. 

maybe just using Media Wiki as a place to draft the guides while we are collaborating on them, and them when they are more polished moving them back into Git? 

Mostly I am coming at this from an efficiency perspective.

**Comment by ridem** [comment]
What about [https://readthedocs.org/](https://readthedocs.org/) for a solidus-doc repository?

This would remove the hassle of setting up a MediaWiki server and to have two different workflows for reviewing changes.
Example: [http://cartodb.readthedocs.org/en/latest/install.html](http://cartodb.readthedocs.org/en/latest/install.html)
The workflow would not be that big of a problem, with the "Edit on Github" button. As it's text, people could edit the docs directly from Github.

**Comment by jasonfb** [comment]
I have no "Edit on Github" button for the Solidus repository and I don't think most people do either--- I think that's reserved for core team members. I think the essence of this endeavor is to broaden the number of people working on this, to take the task of the documentation off the core team's plate.

**Comment by ridem** [comment]
I meant from a [ReadTheDocs](http://cartodb.readthedocs.org/en/latest/install.html) page (top-right corner).
I agree that there's a tradeoff here, but I think most people actually able to contribute to the docs can edit a text on github, and a solidus-doc repository could have a different set of people maintaining it.

**Comment by ajkamel** [comment]
Hey Guys,  I created a repo to get the ball rolling on this and am open to pull requests.  The changes would be made in Markdown in the pages directory and asset images in the top level asset folder.

https://github.com/ajkamel/solidus-guides

ajkamel.github.io/solidus-guides

**Comment by ajkamel** [comment]
Solidus has now adapted this into their repo. Pj's should be sent here https://github.com/solidusio/solidus_guides

**Comment by cbrunsdon** [comment]
Thanks a lot @ajkamel, I think this is an excellent start and a great place for people that want to start contributing documentation.

Very much appreciated. Closing this as we can now use its repo for any conversation about direction of guides.
